// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    GlobalLayout: {
      id: 'GlobalLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true,
    },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'GlobalLayout', isLayout: true },
    DemoLayout: { id: 'DemoLayout', path: '/', parentId: 'GlobalLayout', isLayout: true },
    'uis/checkbox/index': { id: 'uis/checkbox/index', path: 'uis/checkbox', parentId: 'DocLayout' },
    'uis/form/index': { id: 'uis/form/index', path: 'uis/form', parentId: 'DocLayout' },
    'uis/input/index': { id: 'uis/input/index', path: 'uis/input', parentId: 'DocLayout' },
    'uis/radio/index': { id: 'uis/radio/index', path: 'uis/radio', parentId: 'DocLayout' },
    'uis/textarea/index': { id: 'uis/textarea/index', path: 'uis/textarea', parentId: 'DocLayout' },
    'shineouts/checkbox/index': {
      id: 'shineouts/checkbox/index',
      path: 'shineouts/checkbox',
      parentId: 'DocLayout',
    },
    'shineouts/form/index': {
      id: 'shineouts/form/index',
      path: 'shineouts/form',
      parentId: 'DocLayout',
    },
    'shineouts/input/index': {
      id: 'shineouts/input/index',
      path: 'shineouts/input',
      parentId: 'DocLayout',
    },
    'shineouts/radio/index': {
      id: 'shineouts/radio/index',
      path: 'shineouts/radio',
      parentId: 'DocLayout',
    },
    'shineouts/textarea/index': {
      id: 'shineouts/textarea/index',
      path: 'shineouts/textarea',
      parentId: 'DocLayout',
    },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'DemoLayout' },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__404" */ '@/dumi__pages/404'),
      ),
      GlobalLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__GlobalLayout" */ '@/dumi__theme__layouts/GlobalLayout'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__ContextWrapper" */ '@/dumi__theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DocLayout" */ '@/dumi__theme/layouts/DocLayout'
          ),
      ),
      DemoLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DemoLayout" */ '@/dumi__theme/layouts/DemoLayout'
          ),
      ),
      'uis/checkbox/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__base__src__checkbox__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/base/src/checkbox/index.md'
          ),
      ),
      'uis/form/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__base__src__form__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/base/src/form/index.md'
          ),
      ),
      'uis/input/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__base__src__input__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/base/src/input/index.md'
          ),
      ),
      'uis/radio/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__base__src__radio__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/base/src/radio/index.md'
          ),
      ),
      'uis/textarea/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__base__src__textarea__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/base/src/textarea/index.md'
          ),
      ),
      'shineouts/checkbox/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__shineout__src__checkbox__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/shineout/src/checkbox/index.md'
          ),
      ),
      'shineouts/form/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__shineout__src__form__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/shineout/src/form/index.md'
          ),
      ),
      'shineouts/input/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__shineout__src__input__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/shineout/src/input/index.md'
          ),
      ),
      'shineouts/radio/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__shineout__src__radio__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/shineout/src/radio/index.md'
          ),
      ),
      'shineouts/textarea/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__shineout__src__textarea__index.md" */ '/Users/10038185/shineout-next-main/shineout-next/packages/shineout/src/textarea/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__Demo" */ '@/dumi__pages/Demo'),
      ),
    },
  };
}
