// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { InputTokens } from './type';

const inputTokens: InputTokens = {
  inputFontSize: 'Font-14',
  inputBorderRadius: 'Radius-4',
  inputPaddingX: 'Spacing-8',
  inputPaddingY: 'Spacing-4',
  inputIconSize: 'Size-7',
  inputSmallFontSize: 'Font-12',
  inputSmallPaddingX: 'Spacing-8',
  inputSmallPaddingY: 'Spacing-1',
  inputLargeFontSize: 'Font-16',
  inputLargePaddingX: 'Spacing-12',
  inputLargePaddingY: 'Spacing-7',
  inputFontColor: 'Neutral-text-5',
  inputPlaceholderColor: 'Neutral-text-2',
  inputBorderColor: 'Neutral-border-2',
  inputBackgroundColor: 'Neutral-fill-1',
  inputClearColor: 'Neutral-text-3',
  inputToggleColor: 'Neutral-text-4',
  inputIconColor: 'Neutral-text-4',
  inputHoverBorderColor: 'Brand-6',
  inputHoverClearColor: 'Neutral-text-4',
  inputHoverToggleColor: 'Neutral-text-5',
  inputFocusBorderColor: 'Brand-7',
  inputFocusShadow: 'Brand-2',
  inputDisabledFontColor: 'Neutral-text-2',
  inputDisabledPlaceholderColor: 'Neutral-text-2',
  inputDisabledBorderColor: 'Neutral-border-1',
  inputDisabledBackgroundColor: 'Neutral-fill-2',
  inputErrorBorderColor: 'Danger-6',
  inputErrorFocusShadow: 'Danger-1',
  inputInfoFontColor: 'Brand-6',
  inputInfoBackgroundColor: 'Neutral-fill-1',
  inputInfoBorderColor: 'Neutral-border-2',
  inputInfoErrorFontColor: 'Danger-6',
  inputInfoErrorBackgroundColor: 'Danger-1',
  inputInfoErrorBorderColor: 'Danger-6',
  inputInnerPaddingX: 'Spacing-8',
  inputInnerPaddingY: 'Spacing-1',
  inputInnerFontSize: 'Font-12',
  inputInnerSmallPaddingX: 'Spacing-8',
  inputInnerSmallPaddingY: 'Spacing-1',
  inputInnerSmallFontSize: 'Font-12',
  inputInnerLargePaddingX: 'Spacing-12',
  inputInnerLargePaddingY: 'Spacing-3',
  inputInnerLargeFontSize: 'Font-14',
  inputInnerFontColor: 'Neutral-text-4',
};

export default inputTokens;
