// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { InputTokens } from './type';

const input: InputTokens = {
  inputFontColor: '',
  inputBackgroundColor: 'Neutral-Fill-1',
  inputBorderColor: '',
  inputClearIconColor: '',
  inputDisabledFontColor: '',
  inputDisabledBackgroundColor: '',
  inputDisabledBorderColor: '',
  inputDisabledClearIconColor: '',
  inputFocusFontColor: '',
  inputFocusBackgroundColor: '',
  inputFocusBorderColor: '',
  inputFocusClearIconColor: '',
  inputHoverFontColor: '',
  inputHoverBackgroundColor: '',
  inputHoverBorderColor: '',
  inputHoverClearIconColor: '',
  inputErrorFontColor: '',
  inputErrorBackgroundColor: '',
  inputErrorBorderColor: '',
  inputErrorClearIconColor: '',
  inputHeight: '',
  inputFontSize: '',
  inputBorderRadius: '',
  inputBorderWidth: '',
  inputLineHeight: '',
  inputInnerTitleHeight: '',
  inputInnerTitleBorderRadius: '',
  inputInnerTitleLineHeight: '',
  inputClearIconFontSize: '',
  inputPaddingX: '',
  inputPaddingY: '',
  inputSmallHeight: '[object Object]',
  inputSmallFontSize: '',
  inputSmallBorderRadius: '',
  inputSmallBorderWidth: '',
  inputSmallLineHeight: '',
  inputSmallInnerTitleHeight: '',
  inputSmallInnerTitleBorderRadius: '',
  inputSmallInnerTitleLineHeight: '',
  inputSmallClearIconFontSize: '',
  inputSmallPaddingX: '',
  inputSmallPaddingY: '',
  inputLargeHeight: '',
  inputLargeFontSize: '',
  inputLargeBorderRadius: '',
  inputLargeBorderWidth: '',
  inputLargeLineHeight: '',
  inputLargeInnerTitleHeight: '',
  inputLargeInnerTitleBorderRadius: '',
  inputLargeInnerTitleLineHeight: '',
  inputLargeClearIconFontSize: '',
  inputLargePaddingX: '',
  inputLargePaddingY: '',
  inputPrefixFontColor: '',
  inputPrefixBackgroundColor: '',
  inputSuffixFontColor: '',
  inputSuffixBackgroundColor: '',
  inputPrefixPaddingX: '',
  inputPrefixPaddingY: '',
  inputSuffixPaddingX: '',
  inputSuffixPaddingY: '',
  inputSmallPrefixPaddingX: '',
  inputSmallPrefixPaddingY: '',
  inputSmallSuffixPaddingX: '',
  inputSmallSuffixPaddingY: '',
  inputLargePrefixPaddingX: '',
  inputLargePrefixPaddingY: '',
  inputLargeSuffixPaddingX: '',
  inputLargeSuffixPaddingY: '',
  inputIconFontColor: '',
  inputIconBackgroundColor: '',
};

export default input;
