const dark = {
  'Brand-1': '#00174D',
  'Brand-2': '#062C78',
  'Brand-10': '#EDF8FF',
  'Brand-3': '#1046A3',
  'Brand-4': '#1F66CFF9',
  'Brand-5': '#3288FA',
  'Brand-6': '#3F96FB',
  'Brand-7': '#6AB2FC',
  'Brand-8': '#95CDFD',
  'Brand-9': '#C1E3FE',
  'Neutral-fill-8': '#FFFFFFD9',
  'Neutral-text-5': '#FFFFFFD9',
  'Neutral-text-4': '#FFFFFFB3',
  'Neutral-text-3': '#FFFFFF99',
  'Neutral-text-2': '#FFFFFF66',
  'Neutral-border-2': '#FFFFFF42',
  'Neutral-border-1': '#FFFFFF24',
  'Neutral-fill-4': '#333F55',
  'Neutral-fill-3': '#2D364C',
  'Neutral-fill-2': '#21283D',
  'Neutral-fill-1': '#11192E',
  buttonPrimaryDisabledFontColor: 'var(--soui-neutral-text-2)',
  buttonSecondaryFontColor: 'var(--soui-neutral-text-1)',
  buttonWarningDisabledFontColor: 'var(--soui-neutral-text-2)',
  inputFontColor: 'var(--soui-neutral-text-5)',
  selectFontColor: 'var(--soui-neutral-text-1)',
  selectBorderWidth: 'var(--soui-border-2)',
  selectPlaceholderColor: 'var(--soui-neutral-text-2)',
  selectBackgroundColor: 'var(--soui-neutral-fill-2)',
  'Danger-1': '#4D000A',
  'Danger-10': '#FFECE8',
  'Danger-2': '#740813',
  'Danger-3': '#9C1922',
  'Danger-4': '#C33136',
  'Danger-5': '#EB5050',
  'Danger-6': '#EF6C67',
  'Danger-7': '#F38E86',
  'Danger-8': '#F7ADA6',
  'Danger-9': '#FBCDC7',
  'Success-1': '#004D36',
  'Success-2': '#046343',
  'Success-10': '#EBFFF3',
  'Success-3': '#0A7A51',
  'Success-4': '#11915E',
  'Success-5': '#1BA86B',
  'Success-6': '#25B974',
  'Success-7': '#4DCB8C',
  'Success-8': '#7BDCA9',
  'Success-9': '#B0EECB',
  'Warning-1': '#4D1600',
  'Warning-10': '#FFF5E8',
  'Warning-2': '#772804',
  'Warning-3': '#A13F0B',
  'Warning-4': '#CB5C16',
  'Warning-5': '#F57C25',
  'Warning-6': '#F7892F',
  'Warning-7': '#F9A85C',
  'Warning-8': '#FBC58A',
  'Warning-9': '#FDDFB9',
  'Shadow-2': '0px 4px 10px 0px rgba(142, 198, 246, 0.10)',
  'Shadow-3': '0px 8px 20px 0px rgba(236, 243, 255, 0.10)',
  'Shadow-4': '0px -2px 10px 0px rgba(2, 11, 24, 0.08)',
  buttonSuccessDisabledFontColor: 'var(--soui-neutral-text-2)',
  buttonDangerDisabledFontColor: 'var(--soui-neutral-text-2)',
  buttonSecondaryActiveBackgroundColor: 'var(--soui-neutral-fill-4)',
  buttonSecondaryActiveBorderColor: 'var(--soui-neutral-fill-4)',
  popoverBackgroundColor: 'var(--soui-neutral-fill-2)',
  popoverSuccessBackgroundColor: 'var(--soui-success-1)',
  popoverInfoBackgroundColor: 'var(--soui-brand-1)',
  tableTbodyHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  cardBackgroundColor: 'var(--soui-neutral-fill-1)',
  cascaderOptionBackgroundColor: 'var(--soui-neutral-fill-2)',
  tooltipBackgroundColor: 'var(--soui-neutral-fill-3)',
  tooltipLightColor: 'var(--soui-neutral-fill-2)',
  tooltipLightBackgroundColor: 'var(--soui-neutral-text-1)',
  tooltipPrimaryBackgroundColor: 'var(--soui-brand-2)',
  tooltipSuccessColor: 'var(--soui-success-7)',
  treeLineBackgroundColor: 'var(--soui-neutral-border-2)',
  treeContentActiveBackgroundColor: 'var(--soui-brand-1)',
  datePickerCellHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  tagInfoBackgroundColor: 'var(--soui-brand-2)',
  alertInfoBackgroundColor: 'var(--soui-brand-1)',
  messageBackgroundColor: 'var(--soui-neutral-fill-2)',
  progressCircleInfoFontColor: 'var(--soui-neutral-text-5)',
  dropdownListBackgroundColor: 'var(--soui-neutral-fill-2)',
  menuItemActiveBackgroundColor: 'var(--soui-brand-2)',
  dividerFontColor: 'var(--soui-neutral-text-2)',
  cascaderPanelBackgroundColor: 'var(--soui-neutral-fill-2)',
  cascaderOptionDisabledBackgroundColor: 'var(--soui-neutral-fill-2)',
  cascaderOptionHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  datePickerPanelBackgroundColor: 'var(--soui-neutral-fill-2)',
  dropdownOptionHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  treeSelectPanelBackgroundColor: 'var(--soui-neutral-fill-2)',
  treeSelectContentHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  modalPanelBackground: 'var(--soui-neutral-fill-2)',
  dropdownOptionDisabledBackgroundColor: 'var(--soui-neutral-fill-2)',
  messageBorderColor: 'var(--soui-transparent)',
  modalPanelBorder: 'var(--soui-transparent)',
  popoverBorderColor: 'var(--soui-transparent)',
  dropdownOptionBackgroundColor: 'var(--soui-neutral-fill-2)',
  selectPanelBackgroundColor: 'var(--soui-neutral-fill-2)',
  selectOptionBackgroundColor: 'var(--soui-neutral-fill-2)',
  selectOptionHoverBackgroundColor: 'var(--soui-neutral-fill-3)',
  selectOptionDisabledBackgroundColor: 'var(--soui-neutral-fill-2)',
};

const compact = {
  buttonPaddingX: 'var(--soui-spacing-8)',
  buttonPaddingY: 'var(--soui-spacing-2)',
  buttonLargeFontSize: 'var(--soui-font-16)',
  buttonLargePaddingX: 'var(--soui-spacing-12)',
  cardTitleFontSize: 'var(--soui-font-14)',
  cardBodyFontSize: 'var(--soui-font-12)',
  collapseHeaderFontSize: 'var(--soui-font-12)',
  collapseContentFontSize: 'var(--soui-font-12)',
  descriptionsLabelPaddingBottom: 'var(--soui-spacing-12)',
  descriptionsTitleDefaultSize: 'var(--soui-font-16)',
  descriptionsTitleLargeSize: 'var(--soui-font-18)',
  descriptionsFontDefaultSize: 'var(--soui-font-14)',
  descriptionsFontLargeSize: 'var(--soui-font-14)',
  emptyFontSize: 'var(--soui-font-12)',
  listItemPaddingY: 'var(--soui-spacing-8)',
  listItemPaddingX: 'var(--soui-spacing-12)',
  listLargeItemPaddingY: 'var(--soui-spacing-10)',
  listLargeItemPaddingX: 'var(--soui-spacing-12)',
  popoverFontSize: 'var(--soui-font-12)',
  popoverPaddingX: 'var(--soui-spacing-6)',
  popoverPaddingY: 'var(--soui-spacing-4)',
  popoverConfirmPaddingX: 'var(--soui-spacing-12)',
  popoverConfirmPaddingY: 'var(--soui-spacing-12)',
  popoverConfirmMarginY: 'var(--soui-spacing-12)',
  tableCellPaddingX: 'var(--soui-spacing-8)',
  tableCellPaddingY: 'var(--soui-spacing-4)',
  tableCellFontSize: 'var(--soui-font-12)',
  tableLargeTheadFontSize: 'var(--soui-font-12)',
  tableLargeCellPaddingX: 'var(--soui-spacing-12)',
  tableLargeCellPaddingY: 'var(--soui-spacing-8)',
  tableLargeCellFontSize: 'var(--soui-font-12)',
  tableTheadFontSize: 'var(--soui-font-12)',
  tableSmallTheadFontSize: 'var(--soui-font-12)',
  tableSmallCellPaddingX: 'var(--soui-spacing-4)',
  tableSmallCellPaddingY: 'var(--soui-spacing-2)',
  tableSmallCellFontSize: 'var(--soui-font-12)',
  treeSelectTagMarginRight: 'var(--soui-spacing-4)',
  treeSelectTagMarginY: 'var(--soui-spacing-2)',
  buttonLargePaddingY: 'var(--soui-spacing-4)',
  cardHeaderPaddingX: 'var(--soui-spacing-12)',
  cardHeaderPaddingY: 'var(--soui-spacing-8)',
  cardBodyPaddingX: 'var(--soui-spacing-12)',
  cardBodyPaddingY: 'var(--soui-spacing-8)',
  cardFooterPaddingX: 'var(--soui-spacing-12)',
  cardFooterPaddingY: 'var(--soui-spacing-8)',
  cascaderTagMarginY: 'var(--soui-spacing-2)',
  collapseExtraMargin: 'var(--soui-spacing-12)',
  collapseWrapperPaddingX: 'var(--soui-spacing-12)',
  collapseWrapperPaddingY: 'var(--soui-spacing-8)',
  collapseHeaderGap: 'var(--soui-spacing-4)',
  collapseHeaderIconWidth: 'var(--soui-size-6)',
  collapseContentPaddingY: 'var(--soui-spacing-8)',
  collapseContentPaddingLeft: 'var(--soui-spacing-28)',
  collapseContentPaddingRight: 'var(--soui-spacing-12)',
  menuFontSize: 'var(--soui-font-12)',
  menuTitlePaddingX: 'var(--soui-spacing-12)',
  menuTitlePaddingY: 'var(--soui-spacing-8)',
  treePaddingX: 'var(--soui-spacing-4)',
  descriptionsLabelPaddingRight: 'var(--soui-spacing-8)',
  descriptionsBorderPaddingX: 'var(--soui-spacing-4)',
  descriptionsBorderPaddingY: 'var(--soui-spacing-8)',
  descriptionsVerticalPaddingBottom: 'var(--soui-spacing-0)',
  listFontSize: 'var(--soui-font-12)',
  listSmallItemPaddingY: 'var(--soui-spacing-6)',
  listSmallFontSize: 'var(--soui-font-12)',
  checkboxIconSize: 'var(--soui-size-6)',
  checkboxLabelFontSize: 'var(--soui-font-12)',
  checkboxGap: 'var(--soui-spacing-16)',
  checkboxBlockGap: 'var(--soui-spacing-10)',
  checkboxLargeIconSize: 'var(--soui-size-7)',
  checkboxLargeLabelFontSize: 'var(--soui-font-16)',
  inputFontSize: 'var(--soui-font-12)',
  inputLargeFontSize: 'var(--soui-font-16)',
  inputLargePaddingX: 'var(--soui-spacing-8)',
  inputLargePaddingY: 'var(--soui-spacing-4)',
  tagPaddingX: 'var(--soui-spacing-4)',
  tagPaddingY: 'var(--soui-spacing-0)',
  tagLargePaddingX: 'var(--soui-spacing-6)',
  tagLargePaddingY: 'var(--soui-spacing-0)',
  selectFontSize: 'var(--soui-font-12)',
  selectLargeFontSize: 'var(--soui-font-16)',
  selectLargePaddingX: 'var(--soui-spacing-8)',
  selectLargePaddingY: 'var(--soui-spacing-0)',
  selectLargeOptionInnerPaddingX: 'var(--soui-spacing-8)',
  selectTagMarginY: 'var(--soui-spacing-2)',
  selectTagHeight: 'var(--soui-size-9)',
  selectTagLineHeight: 'var(--soui-size-8)',
  alertFontSize: 'var(--soui-font-12)',
  alertFontColor: 'var(--soui-neutral-text-5)',
  alertPaddingX: 'var(--soui-spacing-12)',
  alertPaddingY: 'var(--soui-spacing-8)',
  alertNearlyMargin: 'var(--soui-spacing-8)',
  alertTitleFontSize: 'var(--soui-font-16)',
  alertTitleFontWeight: 'var(--soui-weight-medium)',
  alertTitleMarginY: 'var(--soui-spacing-4)',
  buttonFontSize: 'var(--soui-font-12)',
  dropdownListFontSize: 'var(--soui-font-12)',
  dropdownListLargeFontSize: 'var(--soui-font-14)',
  dropdownOptionLargePaddingX: 'var(--soui-spacing-8)',
  dropdownOptionLargePaddingY: 'var(--soui-spacing-5)',
  modalPanelPaddingY: 'var(--soui-spacing-20)',
  modalPanelPaddingX: 'var(--soui-spacing-20)',
  modalPanelGap: 'var(--soui-spacing-12)',
  modalPanelFontSize: 'var(--soui-font-12)',
  modalHeaderIconMarginEnd: 'var(--soui-spacing-6)',
  modalHeaderIconSize: 'var(--soui-size-7)',
  modalHeaderCloseMarginXStart: 'var(--soui-spacing-12)',
  modalHeaderCloseSize: 'var(--soui-size-7)',
  modalHeaderFontSize: 'var(--soui-font-16)',
  paginationFontSize: 'var(--soui-font-14)',
  buttonSmallPaddingY: 'var(--soui-spacing-2)',
  'Font-14': '12px',
  'Font-16': '14px',
  'Font-18': '16px',
  'Font-20': '18px',
  'Font-24': '20px',
  'Font-28': '24px',
  'Font-32': '28px',
  'Font-36': '32px',
  'Font-48': '36px',
  alertIconSize: 'var(--soui-size-7)',
  breadcrumbSeparatorMarginX: 'var(--soui-spacing-6)',
  checkboxIconGap: 'var(--soui-size-3)',
  datePickerPanelHeaderFontSize: 'var(--soui-font-14)',
  inputPaddingY: 'var(--soui-spacing-4)',
  alertTitleIconWidth: 'var(--soui-size-8)',
  alertTitleIconHeight: 'var(--soui-size-11)',
  inputInnerSmallFontSize: 'var(--soui-font-14)',
  inputInnerTopSmallFontSize: 'var(--soui-font-14)',
  inputInnerTopLargeFontSize: 'var(--soui-font-14)',
  paginationSmallFontSize: 'var(--soui-font-14)',
  paginationLargeFontSize: 'var(--soui-font-16)',
  descriptionsTitleSmallSize: 'var(--soui-font-14)',
  buttonCircleSize: 'var(--soui-size-13)',
  buttonSmallCircleSize: 'var(--soui-size-13)',
  buttonLargeCircleSize: 'var(--soui-size-16)',
};

// const origin = {
//   'Brand-1': '#E9F5FE',
//   'Brand-2': '#BDE2FF',
//   'Brand-10': '#001D61',
//   'Brand-3': '#94CDFF',
//   'Brand-4': '#6BB5FF',
//   'Brand-5': '#429AFF',
//   'Brand-6': '#197AFA',
//   'Brand-7': '#0B5BD4',
//   'Brand-8': '#0040AD',
//   'Brand-9': '#002D87',
//   'Cyan-1': '#E3FEFA',
//   'Cyan-10': '#051F24',
//   'Cyan-2': '#ADF2E9',
//   'Cyan-3': '#7DE3D9',
//   'Cyan-4': '#54D4CC',
//   'Cyan-5': '#34C6C1',
//   'Cyan-6': '#1DB8B9',
//   'Cyan-7': '#158B90',
//   'Cyan-8': '#0D6169',
//   'Cyan-9': '#093D45',
//   'Danger-1': '#FCE6E6',
//   'Danger-10': '#4D000A',
//   'Danger-2': '#F7C1C0',
//   'Danger-3': '#F29896',
//   'Danger-4': '#F38981',
//   'Danger-5': '#EF6661',
//   'Danger-6': '#EB4242',
//   'Danger-7': '#CC2C29',
//   'Danger-8': '#9C161F',
//   'Danger-9': '#740813',
//   'Indigo-1': '#EEF2FE',
//   'Indigo-10': '#170F69',
//   'Indigo-2': '#D7DDFF',
//   'Indigo-3': '#ABB4FB',
//   'Indigo-4': '#848FF9',
//   'Indigo-5': '#6972F6',
//   'Indigo-6': '#4446F7',
//   'Indigo-7': '#3431CD',
//   'Indigo-8': '#2822A6',
//   'Indigo-9': '#1E1782',
//   'Lemon-1': '#FCFADE',
//   'Lemon-10': '#4D3000',
//   'Lemon-2': '#FFF9BF',
//   'Lemon-3': '#FFE76C',
//   'Lemon-4': '#FFE76C',
//   'Lemon-5': '#FFD943',
//   'Lemon-6': '#FFC91A',
//   'Lemon-7': '#D29F10',
//   'Lemon-8': '#A67708',
//   'Lemon-9': '#795203',
//   'Magenta-1': '#FCF1F6',
//   'Magenta-10': '#4B0C37',
//   'Magenta-2': '#F8D8E6',
//   'Magenta-3': '#F3B1D0',
//   'Magenta-4': '#EF8BBE',
//   'Magenta-5': '#E564A8',
//   'Magenta-6': '#D84293',
//   'Magenta-7': '#B4317D',
//   'Magenta-8': '#912266',
//   'Magenta-9': '#6E164E',
//   'Neon-1': '#F1FAE1',
//   'Neon-10': '#194D00',
//   'Neon-2': '#DDF2BE',
//   'Neon-3': '#C4E598',
//   'Neon-4': '#AAD974',
//   'Neon-5': '#90CC54',
//   'Neon-6': '#77BF37',
//   'Neon-7': '#5AA223',
//   'Neon-8': '#418613',
//   'Neon-9': '#2B6908',
//   'Neutral-1': '#000000',
//   'Neutral-10': '#020B18',
//   'Neutral-2': '#F4F5F8',
//   'Neutral-3': '#E8EBF0',
//   'Neutral-4': '#CCCFD7',
//   'Neutral-5': '#B3B7C1',
//   'Neutral-6': '#999DA8',
//   'Neutral-7': '#666C7C',
//   'Neutral-8': '#333E59',
//   'Neutral-9': '#141737',
//   'Orange-1': '#FAF4E3',
//   'Orange-10': '#4D2100',
//   'Orange-2': '#EBDDBC',
//   'Orange-3': '#D6C094',
//   'Orange-4': '#C2A470',
//   'Orange-5': '#AD8951',
//   'Orange-6': '#996F37',
//   'Orange-7': '#865824',
//   'Orange-8': '#734415',
//   'Orange-9': '#603109',
//   'Purple-1': '#F8EEFE',
//   'Purple-10': '#150530',
//   'Purple-2': '#EDD6FE',
//   'Purple-3': '#CFA3F3',
//   'Purple-4': '#AD72E4',
//   'Purple-5': '#8B48D5',
//   'Purple-6': '#6C23C6',
//   'Purple-7': '#4E159E',
//   'Purple-8': '#360C77',
//   'Purple-9': '#220652',
//   'Success-1': '#E4FCED',
//   'Success-2': '#ADEEC9',
//   'Success-10': '#004D36',
//   'Success-3': '#78DCA7',
//   'Success-4': '#4ACB8A',
//   'Success-5': '#22B973',
//   'Success-6': '#00A85F',
//   'Success-7': '#009157',
//   'Success-8': '#007A4D',
//   'Success-9': '#006342',
//   'Tangerine-1': '#FFF0E5',
//   'Tangerine-10': '#56130A',
//   'Tangerine-2': '#FED4B9',
//   'Tangerine-3': '#FDB58F',
//   'Tangerine-4': '#FD9568',
//   'Tangerine-5': '#FD7445',
//   'Tangerine-6': '#F75229',
//   'Tangerine-7': '#CD3A1D',
//   'Tangerine-8': '#A22614',
//   'Tangerine-9': '#7B1B0E',
//   'Warning-1': '#FFF3E2',
//   'Warning-10': '#4D1600',
//   'Warning-2': '#FDDFBA',
//   'Warning-3': '#FBC68D',
//   'Warning-4': '#FDBB66',
//   'Warning-5': '#F78C35',
//   'Warning-6': '#F56C0A',
//   'Warning-7': '#CB5206',
//   'Warning-8': '#A13A03',
//   'Warning-9': '#772601',
//   'Neutral-text-5': '#141737',
//   'Neutral-text-4': '#666C7C',
//   'Neutral-text-3': '#999DA8',
//   'Neutral-text-2': '#B3B7C1',
//   'Neutral-text-1': '#FFFFFF',
//   'Neutral-border-2': '#CCCFD7',
//   'Neutral-border-1': '#E8EBF0',
//   'Neutral-fill-5': '#B3B7C1',
//   'Neutral-fill-9': '#141737',
//   'Neutral-fill-10': '#020B18',
//   'Neutral-fill-6': '#999DA8',
//   'Neutral-fill-8': '#333E59',
//   'Neutral-fill-4': '#CCCFD7',
//   'Neutral-fill-3': '#E8EBF0',
//   'Neutral-fill-2': '#F4F5F8',
//   'Neutral-fill-1': '#FFFFFF',
//   'Padding-1': '1px',
//   'Padding-2': '2px',
//   'Padding-3': '3px',
//   'Padding-4': '4px',
//   'Padding-5': '5px',
//   'Padding-6': '6px',
//   'Padding-7': '7px',
//   'Padding-8': '8px',
//   'Padding-9': '9px',
//   'Padding-10': '10px',
//   'Padding-11': '11px',
//   'Padding-12': '12px',
//   'Padding-13': '13px',
//   'Padding-14': '14px',
//   'Padding-15': '15px',
//   'Padding-16': '16px',
//   'Padding-17': '17px',
//   'Padding-18': '18px',
//   'Padding-19': '19px',
//   'Padding-20': '20px',
//   'Padding-21': '21px',
//   'Padding-22': '22px',
//   'Padding-23': '23px',
//   'Padding-24': '24px',
//   'Margin-4': '4px',
//   'Margin-8': '8px',
//   'Margin-12': '12px',
//   'Margin-16': '16px',
//   'Margin-24': '24px',
//   'Margin-32': '32px',
//   'Radius-0': '0px',
//   'Radius-2': '2px',
//   'Radius-3': '3px',
//   'Radius-4': '4px',
//   'Radius-8': '8px',
//   'Radius-12': '12px',
//   'Radius-1000': '1000px',
//   'Shadow-1': '0px 2px 5px rgba(2, 11, 24, 0.1)',
//   'Shadow-2': '0px 4px 10px rgba(2, 11, 24, 0.1)',
//   'Shadow-3': '0px 8px 20px rgba(2, 11, 24, 0.1)',
//   'Shadow-4': '0px -2px 10px rgba(232, 235, 240, 0.8)',
//   'Line-height-dynamic': 'calc( 1em + 8px )',
//   Transparent: 'transparent',
//   'Mask-fill-1': 'rgba(2, 11, 24, 0.3)',
//   Size: '2',
//   'Radius-rect': '0px',
//   'Radius-lesser': '2px',
//   'Radius-small': '3px',
//   'Radius-default': '4px',
//   'Radius-large': '8px',
//   'Radius-full': '1000px',
//   'Radius-circle': '50%',
//   'Border-0': '0px',
//   'Border-1': '1px',
//   'Border-2': '2px',
//   'Border-3': '3px',
//   'Weight-light': '300',
//   'Weight-regular': '400',
//   'Weight-medium': '500',
//   'Weight-Semibold': '600',
//   'Weight-Bold': '700',
//   'Font-12': '12px',
//   'Font-14': '14px',
//   'Font-16': '16px',
//   'Font-18': '18px',
//   'Font-20': '20px',
//   'Font-24': '24px',
//   'Font-28': '28px',
//   'Font-32': '32px',
//   'Font-36': '36px',
//   'Font-48': '48px',
//   'Spacing-0': '0px',
//   'Spacing-1': '1px',
//   'Spacing-2': '2px',
//   'Spacing-3': '3px',
//   'Spacing-4': '4px',
//   'Spacing-5': '5px',
//   'Spacing-6': '6px',
//   'Spacing-7': '7px',
//   'Spacing-8': '8px',
//   'Spacing-9': '9px',
//   'Spacing-10': '10px',
//   'Spacing-11': '11px',
//   'Spacing-12': '12px',
//   'Spacing-13': '13px',
//   'Spacing-14': '14px',
//   'Spacing-15': '15px',
//   'Spacing-16': '16px',
//   'Spacing-17': '17px',
//   'Spacing-18': '18px',
//   'Spacing-19': '19px',
//   'Spacing-20': '20px',
//   'Spacing-21': '21px',
//   'Spacing-22': '22px',
//   'Spacing-23': '23px',
//   'Spacing-24': '24px',
//   'Spacing-25': '25px',
//   'Spacing-26': '26px',
//   'Spacing-27': '27px',
//   'Spacing-28': '28px',
//   'Spacing-29': '29px',
//   'Spacing-30': '30px',
//   'Spacing-31': '31px',
//   'Spacing-32': '32px',
//   'Spacing-33': '33px',
//   'Spacing-34': '34px',
//   'Spacing-35': '35px',
//   'Spacing-36': '36px',
//   'Spacing-37': '37px',
//   'Spacing-38': '38px',
//   'Spacing-39': '39px',
//   'Spacing-40': '40px',
//   'Spacing-41': '41px',
//   'Spacing-42': '42px',
//   'Spacing-43': '43px',
//   'Spacing-44': '44px',
//   'Spacing-45': '45px',
//   'Spacing-46': '46px',
//   'Spacing-47': '47px',
//   'Spacing-48': '48px',
//   'Size-1': '2px',
//   'Size-2': '4px',
//   'Size-3': '6px',
//   'Size-4': '8px',
//   'Size-5': '10px',
//   'Size-6': '12px',
//   'Size-7': '14px',
//   'Size-8': '16px',
//   'Size-9': '18px',
//   'Size-10': '20px',
//   'Size-11': '22px',
//   'Size-12': '24px',
//   'Size-13': '26px',
//   'Size-14': '28px',
//   'Size-15': '30px',
//   'Size-16': '32px',
//   'Size-17': '34px',
//   'Size-18': '36px',
//   'Size-19': '38px',
//   'Size-20': '40px',
//   'Size-21': '42px',
//   'Size-22': '44px',
//   'Size-23': '46px',
//   'Size-24': '48px',
//   'Size-25': '50px',
//   'Size-26': '52px',
//   'Size-27': '54px',
//   'Size-28': '56px',
// };

export { dark, compact };
