export { default as Alert } from './alert';
export { default as Button } from './button';
export { default as Carousel } from './carousel';
export { default as Checkbox } from './checkbox';
export { default as DatePicker } from './date-picker';
export { default as Divider } from './divider';
export { default as Dropdown } from './dropdown';
export { default as EditableArea } from './editable-area';
export { default as Empty } from './empty';
export { default as Form } from './form';
export { default as Gap } from './gap';
export { default as Icon } from './icon';
export { default as Image } from './image';
export { default as Input } from './input';
export { default as Message } from './message';
export { default as Popover } from './popover';
export { default as Progress } from './progress';
export { default as Radio } from './radio';
export { default as Rate } from './rate';
export { default as Rule } from './rule';
export { default as Spin } from './spin';
export { default as Switch } from './switch';
export { default as Table } from './table';
export { default as Tabs } from './tabs';
export { default as Tag } from './tag';
export { default as Textarea } from './textarea';
export { default as Tooltip } from './tooltip';
export { default as Upload } from './upload';
export { setConfig } from '@sheinx/base';

export * as TYPE from './type';
