// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/10038185/shineout-next-main/shineout-next/node_modules/.pnpm/dumi@2.1.21_@babel+core@7.22.5_@types+node@20.4.0_@types+react@18.2.0_eslint@8.23.0_jest@29.5_4p3h2tlfpdunpw7etllobps54m/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
