// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { DropdownTokens } from './type';

const dropdown: DropdownTokens = {
  dropdownFontColor: '',
  dropdownBackgroundColor: '',
  dropdownBorderColor: '',
  dropdownDisabledFontColor: '',
  dropdownDisabledBackgroundColor: '',
  dropdownDisabledBorderColor: '',
  dropdownHoverFontColor: '',
  dropdownHoverBackgroundColor: '',
  dropdownHoverBorderColor: '',
  dropdownActiveFontColor: '',
  dropdownActiveBackgroundColor: '',
  dropdownActiveBorderColor: '',
  dropdownFocusFontColor: '',
  dropdownFocusBackgroundColor: '',
  dropdownFocusBorderColor: '',
  dropdownOutlineFontColor: '',
  dropdownOutlineBackgroundColor: '',
  dropdownOutlineBorderColor: '',
  dropdownOutlineDisabledFontColor: '',
  dropdownOutlineDisabledBackgroundColor: '',
  dropdownOutlineDisabledBorderColor: '',
  dropdownOutlineHoverFontColor: '',
  dropdownOutlineHoverBackgroundColor: '',
  dropdownOutlineHoverBorderColor: '',
  dropdownOutlineActiveFontColor: '',
  dropdownOutlineActiveBackgroundColor: '',
  dropdownOutlineActiveBorderColor: '',
  dropdownOutlineFocusFontColor: '',
  dropdownOutlineFocusBackgroundColor: '',
  dropdownOutlineFocusBorderColor: '',
  dropdownFontSize: '14/regular',
  dropdownBorderRadius: 'Radius-4',
  dropdownPaddingX: 'Padding-8',
  dropdownPaddingY: 'Padding-5',
  dropdownSmallFontSize: '12/regular',
  dropdownSmallBorderRadius: 'Radius-4',
  dropdownSmallPaddingX: 'Padding-8',
  dropdownSmallPaddingY: 'Padding-2',
  dropdownLargeFontSize: '16/regular',
  dropdownLargeBorderRadius: 'Radius-4',
  dropdownLargePaddingX: 'Padding-12',
  dropdownLargePaddingY: 'Padding-8',
};

export default dropdown;
