// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { DatePickerTokens } from './type';

const datePickerTokens: DatePickerTokens = {
  datePickerFontSize: '14/regular',
  datePickerBorderRadius: 'Radius-4',
  datePickerPaddingX: 'Padding-8',
  datePickerPaddingY: 'Padding-4',
  datePickerIconSize: 'Size-7',
  datePickerSmallFontSize: '12/regular',
  datePickerSmallPaddingX: 'Padding-8',
  datePickerSmallPaddingY: 'Padding-1',
  datePickerLargeFontSize: '16/regular',
  datePickerLargePaddingX: 'Padding-12',
  datePickerLargePaddingY: 'Padding-7',
  datePickerDateWidth: 'Size-120',
  datePickerDateRangeWidth: 'Size-140',
  datePickerDatetimeWidth: 'Size-120',
  datePickerDatetimeRangeWidth: 'Size-210',
  datePickerFontColor: 'Neutral-text-5',
  datePickerPlaceholderColor: 'Neutral-text-2',
  datePickerBorderColor: 'Neutral-border-2',
  datePickerBackgroundColor: 'Neutral-fill-1',
  datePickerClearColor: 'Neutral-text-3',
  datePickerIconColor: 'Neutral-text-4',
  datePickerHoverBorderColor: 'Brand-6',
  datePickerHoverClearColor: 'Neutral-text-4',
  datePickerFocusBorderColor: 'Brand-7',
  datePickerFocusShadow: 'Brand-2',
  datePickerDisabledFontColor: 'Neutral-text-2',
  datePickerDisabledPlaceholderColor: 'Neutral-text-2',
  datePickerDisabledBorderColor: 'Neutral-border-2',
  datePickerDisabledBackgroundColor: 'Neutral-fill-2',
  datePickerErrorBorderColor: 'Danger-6',
  datePickerErrorFocusShadow: 'Danger-1',
  datePickerPickerColor: 'Neutral-text-5',
  datePickerPickerBackgroundColor: 'Neutral-fill-1',
  datePickerPickerShadow: 'Shadow-2',
  datePickerPickerRadius: 'Radius-4',
  datePickerPickerBodyPaddingX: 'Padding-16',
  datePickerPickerBodyPaddingY: 'Padding-16',
  datePickerPickerBodyFontSize: '14/regular',
  datePickerCellColor: 'Neutral-text-5',
  datePickerCellBackgroundColor: 'transparent',
  datePickerCellHoverColor: 'Neutral-text-5',
  datePickerCellHoverBackgroundColor: 'Brand-1',
  datePickerCellActiveColor: 'Neutral-text-1',
  datePickerCellActiveBackgroundColor: 'Brand-6',
  datePickerCellDisabledColor: 'Neutral-text-2',
  datePickerCellDisabledBackgroundColor: 'Neutral-fill-2',
  datePickerCellOtherColor: 'Neutral-text-2',
  datePickerCellHeaderColor: 'Neutral-text-4',
  datePickerCellMarginY: 'Margin-4',
  datePickerDayCellSize: 'Size-16',
  datePickerDayCellHotSize: 'Size-12',
};

export default datePickerTokens;
