const figma = [
  {
    name: '山药品牌色-1',
    value: '#E9F5FE',
    describe: '浅色背景',
    token: 'Brand-1',
  },
  {
    name: '山药品牌色-2',
    value: '#BDE2FF',
    describe: '聚焦',
    token: 'Brand-2',
  },
  {
    name: '山药品牌色-10',
    value: '#001D61',
    describe: '-10',
    token: 'Brand-10',
  },
  {
    name: '山药品牌色-3',
    value: '#94CDFF',
    describe: '禁用',
    token: 'Brand-3',
  },
  {
    name: '山药品牌色-4',
    value: '#6BB5FF',
    describe: '-4',
    token: 'Brand-4',
  },
  {
    name: '山药品牌色-5',
    value: '#429AFF',
    describe: '悬浮',
    token: 'Brand-5',
  },
  {
    name: '山药品牌色-6',
    value: '#197AFA',
    describe: '常规',
    token: 'Brand-6',
  },
  {
    name: '山药品牌色-7',
    value: '#0B5BD4',
    describe: '点击',
    token: 'Brand-7',
  },
  {
    name: '山药品牌色-8',
    value: '#0040AD',
    describe: '-8',
    token: 'Brand-8',
  },
  {
    name: '山药品牌色-9',
    value: '#002D87',
    describe: '-9',
    token: 'Brand-9',
  },
  {
    name: '青色-1',
    value: '#E3FEFA',
    describe: '浅色背景',
    token: 'Cyan-1',
  },
  {
    name: '青色-10',
    value: '#051F24',
    describe: '-10',
    token: 'Cyan-10',
  },
  {
    name: '青色-2',
    value: '#ADF2E9',
    describe: '聚焦',
    token: 'Cyan-2',
  },
  {
    name: '青色-3',
    value: '#7DE3D9',
    describe: '禁用',
    token: 'Cyan-3',
  },
  {
    name: '青色-4',
    value: '#54D4CC',
    describe: '-4',
    token: 'Cyan-4',
  },
  {
    name: '青色-5',
    value: '#34C6C1',
    describe: '悬浮',
    token: 'Cyan-5',
  },
  {
    name: '青色-6',
    value: '#1DB8B9',
    describe: '常规',
    token: 'Cyan-6',
  },
  {
    name: '青色-7',
    value: '#158B90',
    describe: '点击',
    token: 'Cyan-7',
  },
  {
    name: '青色-8',
    value: '#0D6169',
    describe: '-8',
    token: 'Cyan-8',
  },
  {
    name: '青色-9',
    value: '#093D45',
    describe: '-9',
    token: 'Cyan-9',
  },
  {
    name: '危险色-1',
    value: '#FCE6E6',
    describe: '浅色背景',
    token: 'Danger-1',
  },
  {
    name: '危险色-10',
    value: '#4D000A',
    describe: '-10',
    token: 'Danger-10',
  },
  {
    name: '危险色-2',
    value: '#F7C1C0',
    describe: '聚焦',
    token: 'Danger-2',
  },
  {
    name: '危险色-3',
    value: '#F29896',
    describe: '禁用',
    token: 'Danger-3',
  },
  {
    name: '危险色-4',
    value: '#F38981',
    describe: '-4',
    token: 'Danger-4',
  },
  {
    name: '危险色-5',
    value: '#EF6661',
    describe: '悬浮',
    token: 'Danger-5',
  },
  {
    name: '危险色-6',
    value: '#EB4242',
    describe: '常规',
    token: 'Danger-6',
  },
  {
    name: '危险色-7',
    value: '#CC2C29',
    describe: '点击',
    token: 'Danger-7',
  },
  {
    name: '危险色-8',
    value: '#9C161F',
    describe: '-8',
    token: 'Danger-8',
  },
  {
    name: '危险色-9',
    value: '#740813',
    describe: '-9',
    token: 'Danger-9',
  },
  {
    name: '靛蓝色-1',
    value: '#EEF2FE',
    describe: '浅色背景',
    token: 'Indigo-1',
  },
  {
    name: '靛蓝色-10',
    value: '#170F69',
    describe: '-10',
    token: 'Indigo-10',
  },
  {
    name: '靛蓝色-2',
    value: '#D7DDFF',
    describe: '聚焦',
    token: 'Indigo-2',
  },
  {
    name: '靛蓝色-3',
    value: '#ABB4FB',
    describe: '禁用',
    token: 'Indigo-3',
  },
  {
    name: '靛蓝色-4',
    value: '#848FF9',
    describe: '-4',
    token: 'Indigo-4',
  },
  {
    name: '靛蓝色-5',
    value: '#6972F6',
    describe: '悬浮',
    token: 'Indigo-5',
  },
  {
    name: '靛蓝色-6',
    value: '#4446F7',
    describe: '常规',
    token: 'Indigo-6',
  },
  {
    name: '靛蓝色-7',
    value: '#3431CD',
    describe: '点击',
    token: 'Indigo-7',
  },
  {
    name: '靛蓝色-8',
    value: '#2822A6',
    describe: '-8',
    token: 'Indigo-8',
  },
  {
    name: '靛蓝色-9',
    value: '#1E1782',
    describe: '-9',
    token: 'Indigo-9',
  },
  {
    name: '柠檬黄色-1',
    value: '#FCFADE',
    describe: '浅色背景',
    token: 'Lemon-1',
  },
  {
    name: '柠檬黄色-10',
    value: '#4D3000',
    describe: '-10',
    token: 'Lemon-10',
  },
  {
    name: '柠檬黄色-2',
    value: '#FFF9BF',
    describe: '聚焦',
    token: 'Lemon-2',
  },
  {
    name: '柠檬黄色-3',
    value: '#FFE76C',
    describe: '禁用',
    token: 'Lemon-3',
  },
  {
    name: '柠檬黄色-4',
    value: '#FFE76C',
    describe: '-4',
    token: 'Lemon-4',
  },
  {
    name: '柠檬黄色-5',
    value: '#FFD943',
    describe: '悬浮',
    token: 'Lemon-5',
  },
  {
    name: '柠檬黄色-6',
    value: '#FFC91A',
    describe: '常规',
    token: 'Lemon-6',
  },
  {
    name: '柠檬黄色-7',
    value: '#D29F10',
    describe: '点击',
    token: 'Lemon-7',
  },
  {
    name: '柠檬黄色-8',
    value: '#A67708',
    describe: '-8',
    token: 'Lemon-8',
  },
  {
    name: '柠檬黄色-9',
    value: '#795203',
    describe: '-9',
    token: 'Lemon-9',
  },
  {
    name: '洋红色-1',
    value: '#FCF1F6',
    describe: '浅色背景',
    token: 'Magenta-1',
  },
  {
    name: '洋红色-10',
    value: '#4B0C37',
    describe: '-10',
    token: 'Magenta-10',
  },
  {
    name: '洋红色-2',
    value: '#F8D8E6',
    describe: '聚焦',
    token: 'Magenta-2',
  },
  {
    name: '洋红色-3',
    value: '#F3B1D0',
    describe: '禁用',
    token: 'Magenta-3',
  },
  {
    name: '洋红色-4',
    value: '#EF8BBE',
    describe: '-4',
    token: 'Magenta-4',
  },
  {
    name: '洋红色-5',
    value: '#E564A8',
    describe: '悬浮',
    token: 'Magenta-5',
  },
  {
    name: '洋红色-6',
    value: '#D84293',
    describe: '常规',
    token: 'Magenta-6',
  },
  {
    name: '洋红色-7',
    value: '#B4317D',
    describe: '点击',
    token: 'Magenta-7',
  },
  {
    name: '洋红色-8',
    value: '#912266',
    describe: '-8',
    token: 'Magenta-8',
  },
  {
    name: '洋红色-9',
    value: '#6E164E',
    describe: '-9',
    token: 'Magenta-9',
  },
  {
    name: '荧光绿色-1',
    value: '#F1FAE1',
    describe: '浅色背景',
    token: 'Neon-1',
  },
  {
    name: '荧光绿色-10',
    value: '#194D00',
    describe: '-10',
    token: 'Neon-10',
  },
  {
    name: '荧光绿色-2',
    value: '#DDF2BE',
    describe: '聚焦',
    token: 'Neon-2',
  },
  {
    name: '荧光绿色-3',
    value: '#C4E598',
    describe: '禁用',
    token: 'Neon-3',
  },
  {
    name: '荧光绿色-4',
    value: '#AAD974',
    describe: '-4',
    token: 'Neon-4',
  },
  {
    name: '荧光绿色-5',
    value: '#90CC54',
    describe: '悬浮',
    token: 'Neon-5',
  },
  {
    name: '荧光绿色-6',
    value: '#77BF37',
    describe: '常规',
    token: 'Neon-6',
  },
  {
    name: '荧光绿色-7',
    value: '#5AA223',
    describe: '点击',
    token: 'Neon-7',
  },
  {
    name: '荧光绿色-8',
    value: '#418613',
    describe: '-8',
    token: 'Neon-8',
  },
  {
    name: '荧光绿色-9',
    value: '#2B6908',
    describe: '-9',
    token: 'Neon-9',
  },
  {
    name: '中性色-1',
    value: '#000000',
    describe: '浅色背景',
    token: 'Neutral-1',
  },
  {
    name: '中性色-10',
    value: '#020B18',
    describe: '-10',
    token: 'Neutral-10',
  },
  {
    name: '中性色-2',
    value: '#F4F5F8',
    describe: '聚焦',
    token: 'Neutral-2',
  },
  {
    name: '中性色-3',
    value: '#E8EBF0',
    describe: '禁用',
    token: 'Neutral-3',
  },
  {
    name: '中性色-4',
    value: '#CCCFD7',
    describe: '-4',
    token: 'Neutral-4',
  },
  {
    name: '中性色-5',
    value: '#B3B7C1',
    describe: '悬浮',
    token: 'Neutral-5',
  },
  {
    name: '中性色-6',
    value: '#999DA8',
    describe: '常规',
    token: 'Neutral-6',
  },
  {
    name: '中性色-7',
    value: '#666C7C',
    describe: '点击',
    token: 'Neutral-7',
  },
  {
    name: '中性色-8',
    value: '#333E59',
    describe: '-8',
    token: 'Neutral-8',
  },
  {
    name: '中性色-9',
    value: '#141737',
    describe: '-9',
    token: 'Neutral-9',
  },
  {
    name: '橘黄色-1',
    value: '#FAF4E3',
    describe: '浅色背景',
    token: 'Orange-1',
  },
  {
    name: '橘黄色-10',
    value: '#4D2100',
    describe: '-10',
    token: 'Orange-10',
  },
  {
    name: '橘黄色-2',
    value: '#EBDDBC',
    describe: '聚焦',
    token: 'Orange-2',
  },
  {
    name: '橘黄色-3',
    value: '#D6C094',
    describe: '禁用',
    token: 'Orange-3',
  },
  {
    name: '橘黄色-4',
    value: '#C2A470',
    describe: '悬浮',
    token: 'Orange-4',
  },
  {
    name: '橘黄色-5',
    value: '#AD8951',
    describe: '悬浮',
    token: 'Orange-5',
  },
  {
    name: '橘黄色-6',
    value: '#996F37',
    describe: '常规',
    token: 'Orange-6',
  },
  {
    name: '橘黄色-7',
    value: '#865824',
    describe: '点击',
    token: 'Orange-7',
  },
  {
    name: '橘黄色-8',
    value: '#734415',
    describe: '-8',
    token: 'Orange-8',
  },
  {
    name: '橘黄色-9',
    value: '#603109',
    describe: '-9',
    token: 'Orange-9',
  },
  {
    name: '紫色-1',
    value: '#F8EEFE',
    describe: '浅色背景',
    token: 'Purple-1',
  },
  {
    name: '紫色-10',
    value: '#150530',
    describe: '-10',
    token: 'Purple-10',
  },
  {
    name: '紫色-2',
    value: '#EDD6FE',
    describe: '聚焦',
    token: 'Purple-2',
  },
  {
    name: '紫色-3',
    value: '#CFA3F3',
    describe: '禁用',
    token: 'Purple-3',
  },
  {
    name: '紫色-4',
    value: '#AD72E4',
    describe: '-4',
    token: 'Purple-4',
  },
  {
    name: '紫色-5',
    value: '#8B48D5',
    describe: '悬浮',
    token: 'Purple-5',
  },
  {
    name: '紫色-6',
    value: '#6C23C6',
    describe: '常规',
    token: 'Purple-6',
  },
  {
    name: '紫色-7',
    value: '#4E159E',
    describe: '点击',
    token: 'Purple-7',
  },
  {
    name: '紫色-8',
    value: '#360C77',
    describe: '-8',
    token: 'Purple-8',
  },
  {
    name: '紫色-9',
    value: '#220652',
    describe: '-9',
    token: 'Purple-9',
  },
  {
    name: '成功色-1',
    value: '#E4FCED',
    describe: '浅色背景',
    token: 'Success-1',
  },
  {
    name: '成功色-2',
    value: '#ADEEC9',
    describe: '聚焦',
    token: 'Success-2',
  },
  {
    name: '成功色-10',
    value: '#004D36',
    describe: '-10',
    token: 'Success-10',
  },
  {
    name: '成功色-3',
    value: '#78DCA7',
    describe: '禁用',
    token: 'Success-3',
  },
  {
    name: '成功色-4',
    value: '#4ACB8A',
    describe: '-4',
    token: 'Success-4',
  },
  {
    name: '成功色-5',
    value: '#22B973',
    describe: '悬浮',
    token: 'Success-5',
  },
  {
    name: '成功色-6',
    value: '#00A85F',
    describe: '常规',
    token: 'Success-6',
  },
  {
    name: '成功色-7',
    value: '#009157',
    describe: '点击',
    token: 'Success-7',
  },
  {
    name: '成功色-8',
    value: '#007A4D',
    describe: '-8',
    token: 'Success-8',
  },
  {
    name: '成功色-9',
    value: '#006342',
    describe: '-9',
    token: 'Success-9',
  },
  {
    name: '橘红色-1',
    value: '#FFF0E5',
    describe: '浅色背景',
    token: 'Tangerine-1',
  },
  {
    name: '橘红色-10',
    value: '#56130A',
    describe: '-10',
    token: 'Tangerine-10',
  },
  {
    name: '橘红色-2',
    value: '#FED4B9',
    describe: '聚焦',
    token: 'Tangerine-2',
  },
  {
    name: '橘红色-3',
    value: '#FDB58F',
    describe: '禁用',
    token: 'Tangerine-3',
  },
  {
    name: '橘红色-4',
    value: '#FD9568',
    describe: '-4',
    token: 'Tangerine-4',
  },
  {
    name: '橘红色-5',
    value: '#FD7445',
    describe: '悬浮',
    token: 'Tangerine-5',
  },
  {
    name: '橘红色-6',
    value: '#F75229',
    describe: '常规',
    token: 'Tangerine-6',
  },
  {
    name: '橘红色-7',
    value: '#CD3A1D',
    describe: '点击',
    token: 'Tangerine-7',
  },
  {
    name: '橘红色-8',
    value: '#A22614',
    describe: '-8',
    token: 'Tangerine-8',
  },
  {
    name: '橘红色-9',
    value: '#7B1B0E',
    describe: '-9',
    token: 'Tangerine-9',
  },
  {
    name: '警告色-1',
    value: '#FFF3E2',
    describe: '浅色背景',
    token: 'Warning-1',
  },
  {
    name: '警告色-10',
    value: '#4D1600',
    describe: '-10',
    token: 'Warning-10',
  },
  {
    name: '警告色-2',
    value: '#FDDFBA',
    describe: '聚焦',
    token: 'Warning-2',
  },
  {
    name: '警告色-3',
    value: '#FBC68D',
    describe: '禁用',
    token: 'Warning-3',
  },
  {
    name: '警告色-4',
    value: '#FDBB66',
    describe: '-4',
    token: 'Warning-4',
  },
  {
    name: '警告色-5',
    value: '#F78C35',
    describe: '悬浮',
    token: 'Warning-5',
  },
  {
    name: '警告色-6',
    value: '#F56C0A',
    describe: '常规',
    token: 'Warning-6',
  },
  {
    name: '警告色-7',
    value: '#CB5206',
    describe: '点击',
    token: 'Warning-7',
  },
  {
    name: '警告色-8',
    value: '#A13A03',
    describe: '-8',
    token: 'Warning-8',
  },
  {
    name: '警告色-9',
    value: '#772601',
    describe: '-9',
    token: 'Warning-9',
  },

  {
    name: '文字色',
    token: 'Neutral-text-5',
    value: '#141737',
    describe: '主要/正文文字',
  },
  {
    name: '文字色',
    token: 'Neutral-text-4',
    value: '#666C7C',
    describe: '次要文字',
  },
  {
    name: '文字色',
    token: 'Neutral-text-3',
    value: '#999DA8',
    describe: '禁用文字',
  },
  {
    name: '文字色',
    token: 'Neutral-text-2',
    value: '#B3B7C1',
    describe: '占位符文字',
  },
  {
    name: '文字色',
    token: 'Neutral-text-1',
    value: '#FFFFFF',
    describe: '纯白文字',
  },
  {
    name: '边框色',
    token: 'Neutral-border-2',
    value: '#CCCFD7',
    describe: '默认/禁用边框',
  },
  {
    name: '边框色',
    token: 'Neutral-border-1',
    value: '#E8EBF0',
    describe: '分割线',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-5',
    value: '#B3B7C1',
    describe: '点击',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-9',
    value: '#141737',
    describe: '',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-10',
    value: '#020B18',
    describe: '',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-6',
    value: '#999DA8',
    describe: '',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-4',
    value: '#CCCFD7',
    describe: '悬浮',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-3',
    value: '#E8EBF0',
    describe: '常规',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-2',
    value: '#F4F5F8',
    describe: '禁用/表头/底层背景',
  },
  {
    name: '填充色',
    token: 'Neutral-fill-1',
    value: '#FFFFFF',
    describe: '白色背景',
  },
  {
    name: '12/regular',
    token: '12/regular',
    value: '12px',
    describe: '提示、标签、辅助文案',
  },
  {
    name: '12',
    token: 'medium',
    value: '12px',
    describe: '提示、标签、辅助文案',
  },
  {
    name: '14/regular',
    token: '14/regular',
    value: '14px',
    describe: '正文内容',
  },
  {
    name: '14/medium',
    token: '14/medium',
    value: '14px',
    describe: '正文内容突出显示',
  },
  {
    name: '16/regular',
    token: '16/regular',
    value: '16px',
    describe: '标题-小',
  },
  {
    name: '16/medium',
    token: '16/medium',
    value: '16px',
    describe: '标题-小',
  },
  {
    name: '18/regular',
    token: '18/regular',
    value: '18px',
    describe: '标题-中',
  },
  {
    name: '18/medium',
    token: '18/medium',
    value: '18px',
    describe: '标题-中',
  },
  {
    name: '24/regular',
    token: '24/regular',
    value: '24px',
    describe: '标题-大',
  },
  {
    name: '24/medium',
    token: '24/medium',
    value: '24px',
    describe: '标题-大',
  },
  {
    name: '32/regular',
    token: '32/regular',
    value: '32px',
    describe: '运营数据-小',
  },
  {
    name: '32/medium',
    token: '32/medium',
    value: '32px',
    describe: '运营数据-小',
  },
  {
    name: '36/regular',
    token: '36/regular',
    value: '36px',
    describe: '运营数据-中',
  },
  {
    name: '36/medium',
    token: '36/medium',
    value: '36px',
    describe: '运营数据-中',
  },
  {
    name: '48/regular',
    token: '48/regular',
    value: '48px',
    describe: '运营数据-大',
  },
  {
    name: '48/medium',
    token: '48/medium',
    value: '48px',
    describe: '运营数据-大',
  },
  {
    name: '1/padding',
    value: '1px',
    describe: '1 内边距',
    token: 'Padding-1',
  },
  {
    name: '2/padding',
    value: '2px',
    describe: '2 内边距',
    token: 'Padding-2',
  },
  {
    name: '3/padding',
    value: '3px',
    describe: '3 内边距',
    token: 'Padding-3',
  },
  {
    name: '4/padding',
    value: '4px',
    describe: '4 内边距',
    token: 'Padding-4',
  },
  {
    name: '5/padding',
    value: '5px',
    describe: '5 内边距',
    token: 'Padding-5',
  },
  {
    name: '6/padding',
    value: '6px',
    describe: '6 内边距',
    token: 'Padding-6',
  },
  {
    name: '7/padding',
    value: '7px',
    describe: '7 内边距',
    token: 'Padding-7',
  },
  {
    name: '8/padding',
    value: '8px',
    describe: '8 内边距',
    token: 'Padding-8',
  },
  {
    name: '9/padding',
    value: '9px',
    describe: '9 内边距',
    token: 'Padding-9',
  },
  {
    name: '10/padding',
    value: '10px',
    describe: '10 内边距',
    token: 'Padding-10',
  },
  {
    name: '11/padding',
    value: '11px',
    describe: '11 内边距',
    token: 'Padding-11',
  },
  {
    name: '12/padding',
    value: '12px',
    describe: '12 内边距',
    token: 'Padding-12',
  },
  {
    name: '13/padding',
    value: '13px',
    describe: '13 内边距',
    token: 'Padding-13',
  },
  {
    name: '14/padding',
    value: '14px',
    describe: '14 内边距',
    token: 'Padding-14',
  },
  {
    name: '15/padding',
    value: '15px',
    describe: '15 内边距',
    token: 'Padding-15',
  },
  {
    name: '16/padding',
    value: '16px',
    describe: '16 内边距',
    token: 'Padding-16',
  },
  {
    name: '17/padding',
    value: '17px',
    describe: '17 内边距',
    token: 'Padding-17',
  },
  {
    name: '18/padding',
    value: '18px',
    describe: '18 内边距',
    token: 'Padding-18',
  },
  {
    name: '19/padding',
    value: '19px',
    describe: '19 内边距',
    token: 'Padding-19',
  },
  {
    name: '20/padding',
    value: '20px',
    describe: '20 内边距',
    token: 'Padding-20',
  },
  {
    name: '21/padding',
    value: '21px',
    describe: '21 内边距',
    token: 'Padding-21',
  },
  {
    name: '22/padding',
    value: '22px',
    describe: '22 内边距',
    token: 'Padding-22',
  },
  {
    name: '23/padding',
    value: '23px',
    describe: '23 内边距',
    token: 'Padding-23',
  },
  {
    name: '24/padding',
    value: '24px',
    describe: '24 内边距',
    token: 'Padding-24',
  },
  {
    name: '4/margin',
    value: '4px',
    describe: '4 外边距',
    token: 'Margin-4',
  },
  {
    name: '8/margin',
    value: '8px',
    describe: '8 外边距',
    token: 'Margin-8',
  },
  {
    name: '12/margin',
    value: '12px',
    describe: '12 外边距',
    token: 'Margin-12',
  },
  {
    name: '16/margin',
    value: '16px',
    describe: '16 外边距',
    token: 'Margin-16',
  },
  {
    name: '24/margin',
    value: '24px',
    describe: '24 外边距',
    token: 'Margin-24',
  },
  {
    name: '32/margin',
    value: '32px',
    describe: '32 外边距',
    token: 'Margin-32',
  },
  {
    name: '0/radius',
    value: '0px',
    describe: '直角',
    token: 'Radius-0',
  },
  {
    name: '2/radius',
    value: '2px',
    describe: '2 圆角',
    token: 'Radius-2',
  },
  {
    name: '3/radius',
    value: '3px',
    describe: '3 圆角',
    token: 'Radius-3',
  },
  {
    name: '4/radius',
    value: '4px',
    describe: '4 圆角',
    token: 'Radius-4',
  },
  {
    name: '8/radius',
    value: '8px',
    describe: '8 圆角',
    token: 'Radius-8',
  },
  {
    name: '12/radius',
    value: '12px',
    describe: '12 圆角',
    token: 'Radius-12',
  },
  {
    name: '1000/radius',
    value: '1000px',
    describe: '1000 大圆角',
    token: 'Radius-1000',
  },
  {
    name: '50%/radius',
    value: '50%',
    describe: '50% 全圆角',
    token: 'Radius-50%',
  },
  {
    name: '基础阴影',
    value: '0px 2px 5px rgba(2, 11, 24, 0.1)',
    describe: '表格拖拽、树组件拖拽',
    token: 'Shadow-1',
  },
  {
    name: '中阴影',
    value: '0px 4px 10px rgba(2, 11, 24, 0.1)',
    describe: '所有下拉组件使用，下拉菜单、气泡确认框、选择器',
    token: 'Shadow-2',
  },
  {
    name: '重阴影',
    value: '0px 8px 20px rgba(2, 11, 24, 0.1)',
    describe: '所有下拉组件使用，下拉菜单、气泡确认框、选择器',
    token: 'Shadow-3',
  },
  {
    name: 'Shadow-4',
    value: '0px -2px 10px rgba(232, 235, 240, 0.8)',
    describe: '详情页底部按钮模块阴影',
    token: 'Shadow-4',
  },
  {
    name: '动态行高',
    value: 'calc( 1em + 8px )',
    describe: '根据当前的字体大小 + 8px',
    token: 'Line-height-dynamic',
  },
  {
    name: '常规边框',
    value: '1px',
    describe: '常规边框宽度',
    token: 'Border-1',
  },
  {
    name: '较粗边框',
    value: '2px',
    describe: '较粗边框宽度',
    token: 'Border-2',
  },
  {
    name: '粗边框',
    value: '3px',
    describe: '较粗边框宽度',
    token: 'Border-3',
  },
  {
    name: '透明色',
    value: 'transparent',
    describe: '较粗边框宽度',
    token: 'Transparent',
  },
  {
    name: '遮罩填充色',
    value: 'rgba(2, 11, 24, 0.3)',
    describe: '用于遮罩层的带透明度背景色',
    token: 'Mask-fill-1',
  },
  {
    name: '尺寸基数',
    value: '2',
    describe: '尺寸基数，以乘积形式生成所有尺寸，比如：Size * 4px = 8px',
    token: 'Size',
  },
];

const compile = (figmaData) => {
  if (!figmaData) return;
  const result = figmaData.map((i) => {
    if (i.value.indexOf('#') > -1) {
      return {
        ...i,
        type: 'color',
      };
    } else {
      return {
        ...i,
        type: 'string',
      };
    }
  });

  return result;
};

module.exports = {
  figma,
  compile,
};
