// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { RadioTokens } from './type';

const radio: RadioTokens = {
  radioFontColor: '',
  radioBackgroundColor: '',
  radioBorderColor: '',
  radioOutlineFontColor: '',
  radioOutlineBackgroundColor: '',
  radioOutlineBorderColor: '',
  radioDisabledFontColor: '',
  radioDisabledBackgroundColor: '',
  radioDisabledBorderColor: '',
  radioFocusFontColor: '',
  radioFocusBackgroundColor: '',
  radioFocusBorderColor: '',
  radioHoverFontColor: '',
  radioHoverBackgroundColor: '',
  radioHoverBorderColor: '',
  radioButtonFontColor: '',
  radioButtonBackgroundColor: '',
  radioButtonBorderColor: '',
  radioButtonOutlineFontColor: '',
  radioButtonOutlineBackgroundColor: '',
  radioButtonOutlineBorderColor: '',
  radioButtonDisabledFontColor: '',
  radioButtonDisabledBackgroundColor: '',
  radioButtonDisabledBorderColor: '',
  radioButtonFocusFontColor: '',
  radioButtonFocusBackgroundColor: '',
  radioButtonFocusBorderColor: '',
  radioButtonHoverFontColor: '',
  radioButtonHoverBackgroundColor: '',
  radioButtonHoverBorderColor: '',
  radioFontSize: '',
  radioBorderRadius: '',
  radioLineHeight: '',
  radioPaddingX: '',
  radioPaddingY: '',
  radioSmallFontSize: '',
  radioSmallBorderRadius: '',
  radioSmallLineHeight: '',
  radioSmallPaddingX: '',
  radioSmallPaddingY: '',
  radioLargeFontSize: '',
  radioLargeBorderRadius: '',
  radioLargeLineHeight: '',
  radioLargePaddingX: '',
  radioLargePaddingY: '',
};

export default radio;
