export default {
  request: {
    brandPartnerUpsertReq: [
      {
        labelBuildRequest: {
          busId: 1,
          moduleId: 1,
          originalPartnerId: '2296',
          dataId: 2884,
          labelRuleInfo: [
            {
              ruleId: 45,
              ruleFieldList: [
                {
                  fieldId: 77,
                  ruleFieldId: 204,
                  ruleEnumList: [{ fieldEnumId: 33016, ruleFieldEnumId: 66475 }],
                },
                {
                  fieldId: 58,
                  ruleFieldId: 206,
                  ruleEnumList: [{ fieldEnumId: 33142, ruleFieldEnumId: 67179 }],
                },
                { fieldId: 82, ruleFieldId: 210, ruleEnumList: [] },
                { fieldId: 83, ruleFieldId: 211, ruleEnumList: [] },
                { fieldId: 90, ruleFieldId: 227, ruleEnumList: [] },
                { fieldId: 89, ruleFieldId: 228, ruleEnumList: [] },
                { fieldId: 8, ruleFieldId: 229, ruleEnumList: [] },
                {
                  fieldId: 100,
                  ruleFieldId: 240,
                  ruleEnumList: [{ fieldEnumId: 34617, ruleFieldEnumId: 76664 }],
                },
                {
                  fieldId: 98,
                  ruleFieldId: 241,
                  ruleEnumList: [{ fieldEnumId: 34614, ruleFieldEnumId: 76670 }],
                },
                {
                  fieldId: 95,
                  ruleFieldId: 242,
                  ruleEnumList: [{ fieldEnumId: 34605, ruleFieldEnumId: 76673 }],
                },
                {
                  fieldId: 94,
                  ruleFieldId: 243,
                  ruleEnumList: [{ fieldEnumId: 33167, ruleFieldEnumId: 76678 }],
                },
                {
                  fieldId: 102,
                  ruleFieldId: 249,
                  ruleEnumList: [{ fieldEnumId: 34627, ruleFieldEnumId: 76702 }],
                },
                { fieldId: 107, ruleFieldId: 257, ruleEnumList: [] },
              ],
            },
          ],
        },
        updateBrandPartnerRequest: {
          contentTypes: [],
          liveExperience: 0,
          crowdClassification: [],
          cooperateFee: 0,
          feeStyles: [],
          feeChannels: [],
          childBrand: [301],
          description: null,
          cateLine: [],
          fit: 0,
          rsCooperate: 0,
          brandPartnerId: 2884,
          originalPartnerId: '2296',
        },
        brandId: '2',
        brandPartnerId: 2884,
      },
      {
        labelBuildRequest: {
          busId: 1,
          moduleId: 1,
          originalPartnerId: '2296',
          dataId: 2879,
          labelRuleInfo: [
            {
              ruleId: 45,
              ruleFieldList: [
                {
                  fieldId: 77,
                  ruleFieldId: 204,
                  ruleEnumList: [
                    { fieldEnumId: 33143, ruleFieldEnumId: 67180 },
                    { fieldEnumId: 33016, ruleFieldEnumId: 66475 },
                  ],
                },
                {
                  fieldId: 58,
                  ruleFieldId: 206,
                  ruleEnumList: [{ fieldEnumId: 32952, ruleFieldEnumId: 66478 }],
                },
                {
                  fieldId: 82,
                  ruleFieldId: 210,
                  ruleEnumList: [{ fieldEnumId: 33030, ruleFieldEnumId: 66491 }],
                },
                { fieldId: 83, ruleFieldId: 211, ruleEnumList: [] },
                { fieldId: 90, ruleFieldId: 227, ruleEnumList: [] },
                {
                  fieldId: 89,
                  ruleFieldId: 228,
                  ruleEnumList: [{ fieldEnumId: 33148, ruleFieldEnumId: 67213 }],
                },
                { fieldId: 8, ruleFieldId: 229, ruleEnumList: [] },
                {
                  fieldId: 100,
                  ruleFieldId: 240,
                  ruleEnumList: [{ fieldEnumId: 34621, ruleFieldEnumId: 76668 }],
                },
                {
                  fieldId: 98,
                  ruleFieldId: 241,
                  ruleEnumList: [{ fieldEnumId: 34614, ruleFieldEnumId: 76670 }],
                },
                {
                  fieldId: 95,
                  ruleFieldId: 242,
                  ruleEnumList: [{ fieldEnumId: 34606, ruleFieldEnumId: 76674 }],
                },
                {
                  fieldId: 94,
                  ruleFieldId: 243,
                  ruleEnumList: [{ fieldEnumId: 33170, ruleFieldEnumId: 76681 }],
                },
                {
                  fieldId: 102,
                  ruleFieldId: 249,
                  ruleEnumList: [{ fieldEnumId: 34631, ruleFieldEnumId: 76706 }],
                },
                { fieldId: 107, ruleFieldId: 257, ruleEnumList: [] },
              ],
            },
          ],
        },
        updateBrandPartnerRequest: {
          contentTypes: [],
          liveExperience: 0,
          crowdClassification: [],
          cooperateFee: 0,
          feeStyles: [],
          feeChannels: [],
          childBrand: [298, 299, 300, 320, 322],
          description: null,
          takerOrder: 'ONE',
          cateLine: [666, 667, 668],
          fit: 2,
          rsCooperate: 0,
          brandPartnerId: 2879,
          originalPartnerId: '2296',
        },
        brandId: '11',
        brandPartnerId: 2879,
      },
    ],
    commonPartnerUpsertReq: {
      updatePartnerRequest: {
        partnerId: '2296',
        bodyType: '202',
        cooperateFee: '',
        id: 2296,
        partnerProfile: {
          isNew: false,
          isActive: false,
          cooperationStatus: 'IN_COMMUNICATION',
          cooperationTimeLimit: '',
          orderTimeLimit: '',
          releaseTimeLimit: '',
          releaseTimes: 0,
          releaseLinkNumber: 0,
          releasePercent: '0',
          lastShopAddress: null,
          lastCooperateTime: null,
          commonSize: '',
          logisticsTimeLimit: '',
          firstName: '',
          lastName: '',
          country: '',
          province: '',
          city: '',
          address1: '',
          address2: '',
          postcode: '',
          tel: '',
          dress: '',
          makeup: '',
          boutique: '',
          femaleOversize: '',
          yub: '',
          yubClothes: '',
          male: '',
          femaleClothes: '',
          childClothes: '',
          homeLife: '',
          underwearPajamas: '',
          petSupplies: '',
          weddingSpecial: '',
          sports: '',
          motherBaby: '',
          clothingDecorations: '',
          jewelryWatches: '',
          shoes: '',
          bag: '',
        },
        hasAgent: true,
        agents: [
          {
            id: 1222,
            agentId: 6922,
            agentCompanyId: 13,
            agentName: '1234test',
            companyName: 'Warner Music Italy',
            brand: null,
            brandName: null,
            mainContactType: 'E_MAIL',
            mainContactTypeName: null,
            mainContact: '123@163.com',
            contacts: null,
            marketingSupplierId: 384,
            marketingSupplierName: 'hexiansen123333333',
            UUID: 0,
          },
        ],
        channels: [
          {
            id: 5644,
            channelType: 10,
            mainUrl: 'https://www.pinterest.com/sdfdsf',
            username: 'sdfdsf',
            fansAmount: 3001,
            femaleFansPercent: 100,
            isMain: true,
            level: 'F',
            spiderTime: null,
            mainUrlState: 0,
            interactionQuality: '',
            audienceAge: 213,
            audienceEthnicity: 0,
            countryFansPercentInfo: [
              { country: 9, countryName: 'Antigua and Barbuda', percent: 1 },
            ],
            labelInfo: {
              busId: 1,
              moduleId: 2,
              labelRuleInfo: [
                {
                  ruleId: 50,
                  ruleFieldList: [
                    { fieldId: 93, ruleFieldId: 225, ruleEnumList: [] },
                    {
                      fieldId: 94,
                      ruleFieldId: 226,
                      ruleEnumList: [{ fieldEnumId: 33170, ruleFieldEnumId: 67207 }],
                    },
                    {
                      fieldId: 90,
                      ruleFieldId: 222,
                      ruleEnumList: [{ fieldEnumId: 33150, ruleFieldEnumId: 67187 }],
                    },
                    { fieldId: 89, ruleFieldId: 221, ruleEnumList: [] },
                    {
                      fieldId: 104,
                      ruleFieldId: 251,
                      ruleEnumList: [{ fieldEnumId: 34641, ruleFieldEnumId: 76716 }],
                    },
                    {
                      fieldId: 105,
                      ruleFieldId: 252,
                      ruleEnumList: [{ fieldEnumId: 34649, ruleFieldEnumId: 76724 }],
                    },
                    { fieldId: 106, ruleFieldId: 253, ruleEnumList: [] },
                  ],
                },
              ],
            },
            avgView: 0,
            avgLikes: 0,
            authorization: 0,
            isInvalid: 0,
          },
          {
            id: 5640,
            channelType: 1,
            mainUrl: 'https://www.instagram.com/112233test',
            username: '112233test',
            fansAmount: 55,
            femaleFansPercent: 30,
            isMain: false,
            level: 'F',
            spiderTime: null,
            mainUrlState: 0,
            interactionQuality: '400',
            audienceAge: 214,
            audienceEthnicity: 0,
            countryFansPercentInfo: [{ country: 1, countryName: 'Afghanistan', percent: 1 }],
            labelInfo: {
              busId: 1,
              moduleId: 2,
              labelRuleInfo: [
                {
                  ruleId: 50,
                  ruleFieldList: [
                    { fieldId: 93, ruleFieldId: 225, ruleEnumList: [] },
                    {
                      fieldId: 94,
                      ruleFieldId: 226,
                      ruleEnumList: [{ fieldEnumId: 33170, ruleFieldEnumId: 67207 }],
                    },
                    {
                      fieldId: 90,
                      ruleFieldId: 222,
                      ruleEnumList: [{ fieldEnumId: 33151, ruleFieldEnumId: 67188 }],
                    },
                    { fieldId: 89, ruleFieldId: 221, ruleEnumList: [] },
                    { fieldId: 104, ruleFieldId: 251, ruleEnumList: [] },
                    { fieldId: 105, ruleFieldId: 252, ruleEnumList: [] },
                    { fieldId: 106, ruleFieldId: 253, ruleEnumList: [] },
                  ],
                },
              ],
            },
            avgView: 60,
            avgLikes: 72,
            authorization: 0,
            isInvalid: 0,
          },
        ],
        contacts: [
          { id: 2699, remark: '测试第三次', type: 'E_MAIL', contact: '12312312@.qwecom', UUID: 0 },
        ],
        avatar: '',
        username: '测试0719',
        gender: 2,
        bodyTypeName: null,
        email: 'willow_kuangqew11232@qq_test.com',
        color: 1,
        ageGroup: '',
        ageGroupName: null,
        partnerStyle: [],
        partnerStyleName: null,
        crowdClassification: null,
        crowdClassificationName: null,
        hobby: [],
        hobbyName: null,
        religiousBelief: [],
        religiousBeliefName: null,
        specialOutfit: [],
        specialOutfitName: null,
        career: [],
        careerName: null,
        badRecord: [],
        badRecordName: null,
        majorFanCountryName: null,
        countryFansPercentInfo: null,
        accountProtagonist: [],
        accountProtagonistName: null,
        feeChannels: [],
        feeStyles: [],
        market: 1,
        mainTeamId: 1,
        managerName: 'Pony Ma(10026275)',
        race: '',
        raceName: null,
        language: ['1'],
        languageName: null,
        materialQuality: '',
        materialQualityName: null,
        materialForm: '',
        materialFormName: null,
        interactionQuality: '',
        liveExperienceNew: null,
        liveExperienceName: null,
        takerOrder: 'FIVE',
        description: '',
        shootType: [],
        shootTypeName: null,
        insertTime: '2024-07-19 17:34:46',
        insertUser: 'Yoyo Yu(10027078)',
        assigmentTime: null,
        teamInfo: [
          { teamId: 1, teamName: '营销团队' },
          { teamId: 2, teamName: '市场团队' },
          { teamId: 3, teamName: '品牌团队' },
          { teamId: 4, teamName: '其他团队' },
        ],
        marketingSupplierId: null,
        marketingSupplierName: null,
        birthday: null,
        age: '',
        cateLine: [
          { brandName: 'SHEIN', cateLineId: 666, cateLineName: null },
          { brandName: 'SHEIN', cateLineId: 667, cateLineName: null },
          { brandName: 'SHEIN', cateLineId: 668, cateLineName: null },
        ],
        seriesLine: [
          { brandName: 'ROMWE', seriesLineId: 301, seriesLineName: null },
          { brandName: 'ROMWE', seriesLineId: 301, seriesLineName: null },
          { brandName: 'SHEIN', seriesLineId: 298, seriesLineName: null },
          { brandName: 'SHEIN', seriesLineId: 299, seriesLineName: null },
          { brandName: 'SHEIN', seriesLineId: 300, seriesLineName: null },
          { brandName: 'SHEIN', seriesLineId: 320, seriesLineName: null },
          { brandName: 'SHEIN', seriesLineId: 322, seriesLineName: null },
        ],
        userTeam: [
          { id: '1', name: '营销团队', searchParamInfo: null, children: null },
          { id: '2', name: '市场团队', searchParamInfo: null, children: null },
          { id: '3', name: '品牌团队', searchParamInfo: null, children: null },
          { id: '4', name: '其他团队', searchParamInfo: null, children: null },
        ],
      },
      labelBuildRequest: {
        busId: 1,
        moduleId: 3,
        originalPartnerId: 2296,
        dataId: 2296,
        labelRuleInfo: [
          {
            ruleId: 51,
            ruleFieldList: [
              { fieldId: 77, ruleFieldId: 231, ruleEnumList: [] },
              { fieldId: 98, ruleFieldId: 236, ruleEnumList: [] },
              { fieldId: 100, ruleFieldId: 237, ruleEnumList: [] },
              { fieldId: 99, ruleFieldId: 238, ruleEnumList: [] },
              {
                fieldId: 95,
                ruleFieldId: 239,
                ruleEnumList: [{ fieldEnumId: 34604, ruleFieldEnumId: 76660 }],
              },
              {
                fieldId: 102,
                ruleFieldId: 255,
                ruleEnumList: [{ fieldEnumId: 34630, ruleFieldEnumId: 76744 }],
              },
              {
                fieldId: 107,
                ruleFieldId: 256,
                ruleEnumList: [{ fieldEnumId: 34659, ruleFieldEnumId: 76753 }],
              },
            ],
          },
        ],
      },
      partnerId: '2296',
    },
  },
  resourceType: 'brandPoolEditKol',
};
