export * from './is';
export { default as extractEventHandlers } from './extractEventHandlers';
export * from './clone';
export * from './object';
export * from './string';
export * from './func';
export * from './validate';
export * from './number';
export * from './shallowEqual';
export * from './uid';
export * from './document';
