// 此文件由脚本自动生成，请勿直接修改。
// This file was generated automatically by a script. Please do not modify it directly.

import { TagTokens } from './type';

const tag: TagTokens = {
  tagInfoFontColor: 'Brand-6',
  tagInfoBackgroundColor: 'Brand-1',
  tagInfoBorderColor: 'Brand-1',
  tagInfoDisabledFontColor: 'Brand-3',
  tagInfoDisabledBackgroundColor: 'Brand-1',
  tagInfoDisabledBorderColor: 'Brand-1',
  tagInfoOutlineFontColor: 'Brand-6',
  tagInfoOutlineBackgroundColor: 'Neutral-fill-1',
  tagInfoOutlineBorderColor: 'Brand-6',
  tagInfoOutlineDisabledFontColor: 'Brand-3',
  tagInfoOutlineDisabledBackgroundColor: 'Neutral-fill-1',
  tagInfoOutlineDisabledBorderColor: 'Brand-3',
  tagDefaultFontColor: 'Neutral-text-5',
  tagDefaultBackgroundColor: 'Neutral-fill-2',
  tagDefaultBorderColor: 'Neutral-fill-2',
  tagDefaultDisabledFontColor: 'Neutral-text-2',
  tagDefaultDisabledBackgroundColor: 'Neutral-fill-2',
  tagDefaultDisabledBorderColor: 'Neutral-fill-2',
  tagDefaultOutlineFontColor: 'Neutral-text-4',
  tagDefaultOutlineBackgroundColor: 'Neutral-fill-1',
  tagDefaultOutlineBorderColor: 'Neutral-border-2',
  tagDefaultOutlineDisabledFontColor: 'Neutral-text-2',
  tagDefaultOutlineDisabledBackgroundColor: 'Neutral-fill-1',
  tagDefaultOutlineDisabledBorderColor: 'Neutral-border-2',
  tagSuccessFontColor: 'Success-6',
  tagSuccessBackgroundColor: 'Success-1',
  tagSuccessBorderColor: 'Success-1',
  tagSuccessDisabledFontColor: 'Success-3',
  tagSuccessDisabledBackgroundColor: 'Success-1',
  tagSuccessDisabledBorderColor: 'Success-1',
  tagSuccessOutlineFontColor: 'Success-5',
  tagSuccessOutlineBackgroundColor: 'Neutral-fill-1',
  tagSuccessOutlineBorderColor: 'Success-5',
  tagSuccessOutlineDisabledFontColor: 'Success-3',
  tagSuccessOutlineDisabledBackgroundColor: 'Neutral-fill-1',
  tagSuccessOutlineDisabledBorderColor: 'Success-3',
  tagWarningFontColor: 'Warning-6',
  tagWarningBackgroundColor: 'Warning-1',
  tagWarningBorderColor: 'Warning-1',
  tagWarningDisabledFontColor: 'Warning-3',
  tagWarningDisabledBackgroundColor: 'Warning-1',
  tagWarningDisabledBorderColor: 'Warning-1',
  tagWarningOutlineFontColor: 'Warning-5',
  tagWarningOutlineBackgroundColor: 'Neutral-fill-1',
  tagWarningOutlineBorderColor: 'Warning-5',
  tagWarningOutlineDisabledFontColor: 'Warning-3',
  tagWarningOutlineDisabledBackgroundColor: 'Neutral-fill-1',
  tagWarningOutlineDisabledBorderColor: 'Warning-3',
  tagDangerFontColor: 'Danger-6',
  tagDangerBackgroundColor: 'Danger-1',
  tagDangerBorderColor: 'Danger-1',
  tagDangerDisabledFontColor: 'Danger-3',
  tagDangerDisabledBackgroundColor: 'Danger-1',
  tagDangerDisabledBorderColor: 'Danger-1',
  tagDangerOutlineFontColor: 'Danger-5',
  tagDangerOutlineBackgroundColor: 'Neutral-fill-1',
  tagDangerOutlineBorderColor: 'Danger-5',
  tagDangerOutlineDisabledFontColor: 'Danger-3',
  tagDangerOutlineDisabledBackgroundColor: 'Neutral-fill-1',
  tagDangerOutlineDisabledBorderColor: 'Danger-3',
  tagFontSize: '12/regular',
  tagBorderRadius: 'Radius-2',
  tagPaddingX: 'Padding-6',
  tagPaddingY: 'Padding-2',
  tagHeight: 'Size-12',
  tagSmallFontSize: '12/regular',
  tagSmallBorderRadius: 'Radius-2',
  tagSmallPaddingX: 'Padding-4',
  tagSmallHeight: 'Size-10',
  tagLargeFontSize: '14/regular',
  tagLargeBorderRadius: 'Radius-4',
  tagLargePaddingX: 'Padding-12',
  tagLargePaddingY: 'Padding-3',
  tagLargeHeight: 'Size-20',
};

export default tag;
