// This file is auto-generated by scripts/generate-diff-imports.js
// DO NOT EDIT MANUALLY

import alert_3_1_31 from '!!raw-loader!../../../packages/shineout/src/alert/__diff__/3.1.31/index.md';
import alert_3_2_5 from '!!raw-loader!../../../packages/shineout/src/alert/__diff__/3.2.5/index.md';
import alert_3_7_0_beta_35 from '!!raw-loader!../../../packages/shineout/src/alert/__diff__/3.7.0-beta.35/index.md';
import alert_3_7_5_beta_10 from '!!raw-loader!../../../packages/shineout/src/alert/__diff__/3.7.5-beta.10/index.md';
import badge_3_5_2 from '!!raw-loader!../../../packages/shineout/src/badge/__diff__/3.5.2/index.md';
import breadcrumb_3_7_6_beta_3 from '!!raw-loader!../../../packages/shineout/src/breadcrumb/__diff__/3.7.6-beta.3/index.md';
import button_3_0_2 from '!!raw-loader!../../../packages/shineout/src/button/__diff__/3.0.2/index.md';
import button_3_1_2 from '!!raw-loader!../../../packages/shineout/src/button/__diff__/3.1.2/index.md';
import button_3_1_30 from '!!raw-loader!../../../packages/shineout/src/button/__diff__/3.1.30/index.md';
import button_3_5_3 from '!!raw-loader!../../../packages/shineout/src/button/__diff__/3.5.3/index.md';
import button_3_7_0_beta_24 from '!!raw-loader!../../../packages/shineout/src/button/__diff__/3.7.0-beta.24/index.md';
import card_3_1_10 from '!!raw-loader!../../../packages/shineout/src/card/__diff__/3.1.10/index.md';
import card_3_1_16 from '!!raw-loader!../../../packages/shineout/src/card/__diff__/3.1.16/index.md';
import card_3_1_23 from '!!raw-loader!../../../packages/shineout/src/card/__diff__/3.1.23/index.md';
import card_3_6_1_beta_8 from '!!raw-loader!../../../packages/shineout/src/card/__diff__/3.6.1-beta.8/index.md';
import carousel_3_4_0 from '!!raw-loader!../../../packages/shineout/src/carousel/__diff__/3.4.0/index.md';
import carousel_3_6_0 from '!!raw-loader!../../../packages/shineout/src/carousel/__diff__/3.6.0/index.md';
import carousel_3_6_0_beta_1 from '!!raw-loader!../../../packages/shineout/src/carousel/__diff__/3.6.0-beta.1/index.md';
import carousel_3_7_0_beta_37 from '!!raw-loader!../../../packages/shineout/src/carousel/__diff__/3.7.0-beta.37/index.md';
import carousel_3_7_0_beta_38 from '!!raw-loader!../../../packages/shineout/src/carousel/__diff__/3.7.0-beta.38/index.md';
import checkbox_3_3_7 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.3.7/index.md';
import checkbox_3_4_3 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.4.3/index.md';
import checkbox_3_5_6 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.5.6/index.md';
import checkbox_3_5_8 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.5.8/index.md';
import checkbox_3_6_0 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.6.0/index.md';
import checkbox_3_6_0_beta_1 from '!!raw-loader!../../../packages/shineout/src/checkbox/__diff__/3.6.0-beta.1/index.md';
import collapse_3_6_0 from '!!raw-loader!../../../packages/shineout/src/collapse/__diff__/3.6.0/index.md';
import date_picker_3_4_0 from '!!raw-loader!../../../packages/shineout/src/date-picker/__diff__/3.4.0/index.md';
import date_picker_3_6_0 from '!!raw-loader!../../../packages/shineout/src/date-picker/__diff__/3.6.0/index.md';
import date_picker_3_6_7_beta_6 from '!!raw-loader!../../../packages/shineout/src/date-picker/__diff__/3.6.7-beta.6/index.md';
import date_picker_3_7_4_beta_6 from '!!raw-loader!../../../packages/shineout/src/date-picker/__diff__/3.7.4-beta.6/index.md';
import date_picker_3_7_5_beta_5 from '!!raw-loader!../../../packages/shineout/src/date-picker/__diff__/3.7.5-beta.5/index.md';
import drawer_3_0_5 from '!!raw-loader!../../../packages/shineout/src/drawer/__diff__/3.0.5/index.md';
import dropdown_3_3_2 from '!!raw-loader!../../../packages/shineout/src/dropdown/__diff__/3.3.2/index.md';
import dropdown_3_3_3 from '!!raw-loader!../../../packages/shineout/src/dropdown/__diff__/3.3.3/index.md';
import dropdown_3_4_0 from '!!raw-loader!../../../packages/shineout/src/dropdown/__diff__/3.4.0/index.md';
import dropdown_3_6_0 from '!!raw-loader!../../../packages/shineout/src/dropdown/__diff__/3.6.0/index.md';
import input_3_5_7 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.5.7/index.md';
import input_3_5_8 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.5.8/index.md';
import input_3_6_0 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.6.0/index.md';
import input_3_6_0_beta_22 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.6.0-beta.22/index.md';
import input_3_7_3_beta_1 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.7.3-beta.1/index.md';
import input_3_7_3_beta_4 from '!!raw-loader!../../../packages/shineout/src/input/__diff__/3.7.3-beta.4/index.md';

export const diffReports: Record<string, string> = {
  'alert/3.1.31': alert_3_1_31,
  'alert/3.2.5': alert_3_2_5,
  'alert/3.7.0-beta.35': alert_3_7_0_beta_35,
  'alert/3.7.5-beta.10': alert_3_7_5_beta_10,
  'badge/3.5.2': badge_3_5_2,
  'breadcrumb/3.7.6-beta.3': breadcrumb_3_7_6_beta_3,
  'button/3.0.2': button_3_0_2,
  'button/3.1.2': button_3_1_2,
  'button/3.1.30': button_3_1_30,
  'button/3.5.3': button_3_5_3,
  'button/3.7.0-beta.24': button_3_7_0_beta_24,
  'card/3.1.10': card_3_1_10,
  'card/3.1.16': card_3_1_16,
  'card/3.1.23': card_3_1_23,
  'card/3.6.1-beta.8': card_3_6_1_beta_8,
  'carousel/3.4.0': carousel_3_4_0,
  'carousel/3.6.0': carousel_3_6_0,
  'carousel/3.6.0-beta.1': carousel_3_6_0_beta_1,
  'carousel/3.7.0-beta.37': carousel_3_7_0_beta_37,
  'carousel/3.7.0-beta.38': carousel_3_7_0_beta_38,
  'checkbox/3.3.7': checkbox_3_3_7,
  'checkbox/3.4.3': checkbox_3_4_3,
  'checkbox/3.5.6': checkbox_3_5_6,
  'checkbox/3.5.8': checkbox_3_5_8,
  'checkbox/3.6.0': checkbox_3_6_0,
  'checkbox/3.6.0-beta.1': checkbox_3_6_0_beta_1,
  'collapse/3.6.0': collapse_3_6_0,
  'date-picker/3.4.0': date_picker_3_4_0,
  'date-picker/3.6.0': date_picker_3_6_0,
  'date-picker/3.6.7-beta.6': date_picker_3_6_7_beta_6,
  'date-picker/3.7.4-beta.6': date_picker_3_7_4_beta_6,
  'date-picker/3.7.5-beta.5': date_picker_3_7_5_beta_5,
  'drawer/3.0.5': drawer_3_0_5,
  'dropdown/3.3.2': dropdown_3_3_2,
  'dropdown/3.3.3': dropdown_3_3_3,
  'dropdown/3.4.0': dropdown_3_4_0,
  'dropdown/3.6.0': dropdown_3_6_0,
  'input/3.5.7': input_3_5_7,
  'input/3.5.8': input_3_5_8,
  'input/3.6.0': input_3_6_0,
  'input/3.6.0-beta.22': input_3_6_0_beta_22,
  'input/3.7.3-beta.1': input_3_7_3_beta_1,
  'input/3.7.3-beta.4': input_3_7_3_beta_4
};

export const diffReportsList = [
  { component: 'alert', version: '3.1.31' },
  { component: 'alert', version: '3.2.5' },
  { component: 'alert', version: '3.7.0-beta.35' },
  { component: 'alert', version: '3.7.5-beta.10' },
  { component: 'badge', version: '3.5.2' },
  { component: 'breadcrumb', version: '3.7.6-beta.3' },
  { component: 'button', version: '3.0.2' },
  { component: 'button', version: '3.1.2' },
  { component: 'button', version: '3.1.30' },
  { component: 'button', version: '3.5.3' },
  { component: 'button', version: '3.7.0-beta.24' },
  { component: 'card', version: '3.1.10' },
  { component: 'card', version: '3.1.16' },
  { component: 'card', version: '3.1.23' },
  { component: 'card', version: '3.6.1-beta.8' },
  { component: 'carousel', version: '3.4.0' },
  { component: 'carousel', version: '3.6.0' },
  { component: 'carousel', version: '3.6.0-beta.1' },
  { component: 'carousel', version: '3.7.0-beta.37' },
  { component: 'carousel', version: '3.7.0-beta.38' },
  { component: 'checkbox', version: '3.3.7' },
  { component: 'checkbox', version: '3.4.3' },
  { component: 'checkbox', version: '3.5.6' },
  { component: 'checkbox', version: '3.5.8' },
  { component: 'checkbox', version: '3.6.0' },
  { component: 'checkbox', version: '3.6.0-beta.1' },
  { component: 'collapse', version: '3.6.0' },
  { component: 'date-picker', version: '3.4.0' },
  { component: 'date-picker', version: '3.6.0' },
  { component: 'date-picker', version: '3.6.7-beta.6' },
  { component: 'date-picker', version: '3.7.4-beta.6' },
  { component: 'date-picker', version: '3.7.5-beta.5' },
  { component: 'drawer', version: '3.0.5' },
  { component: 'dropdown', version: '3.3.2' },
  { component: 'dropdown', version: '3.3.3' },
  { component: 'dropdown', version: '3.4.0' },
  { component: 'dropdown', version: '3.6.0' },
  { component: 'input', version: '3.5.7' },
  { component: 'input', version: '3.5.8' },
  { component: 'input', version: '3.6.0' },
  { component: 'input', version: '3.6.0-beta.22' },
  { component: 'input', version: '3.7.3-beta.1' },
  { component: 'input', version: '3.7.3-beta.4' }
];
