// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/10038185/shineout-next-main/shineout-next/node_modules/dumi-theme-antd-style/dist/builtins/SourceCode/index.js';
