export default [
  {
    "overdueStatus": null,
    "invalidType": 0,
    "invalidTypeName": "",
    "customizedOrder": 2,
    "firstMark": 2,
    "skcCopyFlag": 2,
    "orderLabels": [
      {
        "labelId": 17,
        "labelName": "",
        "labelRemark": ""
      },
      {
        "labelId": 40,
        "labelName": "Gabi Martins",
        "labelRemark": null
      },
      {
        "labelId": 214,
        "labelName": "阻燃款定采",
        "labelRemark": "根据PLM提供的阻燃定采商品标签判断是否打该订单标签，如打上此订单标签，则需要供应商在生产前，去指定采购阻燃面料；"
      }
    ],
    "goodsLabels": [],
    "prepareTypeId": 9,
    "prepareTypeName": "JIT备货",
    "invalidTime": "",
    "id": 3040166,
    "orderId": 1741561,
    "sellerOrderNo": "PB2412020000044",
    "orderType": 2,
    "orderTypeName": "备货",
    "state": 2,
    "stateName": "待发货",
    "deliveryTime": "",
    "deliveryNo": "",
    "currencyId": 156,
    "currencyCode": "CNY",
    "currentCostTime": 0,
    "remainSendTime": null,
    "requestDeliveryTime": "",
    "finishTime": "",
    "allocateTime": "2024-12-02 14:27:14",
    "addTime": "2024-12-02 14:27:14",
    "receiptTime": "",
    "storageId": 1,
    "storageName": "佛山仓",
    "isFoShanStorage": 1,
    "recommendedSubWarehouseId": 26247,
    "recommendedSubWarehouseName": "",
    "paymentType": 2,
    "paymentTypeName": "备货入库结算",
    "orderLabel": null,
    "orderHasTracingTag": 1,
    "entirelyDistribute": 2,
    "lackMaterialCanDeliver": 2,
    "bomVersion": 0,
    "detail": [
      {
        "id": 3040166,
        "needQuantity": 1,
        "suffixZh": "明亮-M(中文)",
        "subSuffixZh": "M(中文)",
        "skuCode": "I9bqmdwce10i",
        "billState": 0,
        "skuThumb": "",
        "billStateName": "未维护",
        "orderQuantity": 1,
        "deliveryQuantity": null,
        "storageQuantity": null,
        "defectiveQuantity": null,
        "receiptQuantity": null,
        "groundingQuantity": null,
        "returnPlanQuantity": null,
        "supplierSku": "",
        "supplyPrice": 14.64,
        "tempDeliveryQuantity": 0,
        "tempPackingDetail": null
      }
    ],
    "goods": {
      "goodsLevel": 17,
      "categoryId": 2339,
      "goodsLevelName": "新款",
      "imgPath": "http://imgdeal-test01.shein.com/images3_pi/2022/12/27/16721256191377985597.jpg",
      "goodsThumb": "",
      "smallImgPath": "http://imgdeal-test01.shein.com/images3_pi/2022/12/27/16721256191377985597.jpg",
      "skcName": "ss22120144519212",
      "productType": null,
      "supplierCode": "1"
    },
    "skcName": "ss22120144519212",
    "productType": null,
    "packageNum": null,
    "exportingMode": null,
    "exportingModeName": null,
    "outTaxRate": null,
    "safeFlag": 1,
    "attributeVersion": -1,
    "hasOrderReportTag": null,
    "reportStatus": null,
    "reportStatusName": null,
    "isCustomerSupply": null,
    "customerSupplyCanDeliver": null,
    "controlStatus": null,
    "consumableBomVersion": null,
    "requestTakeParcelTime": "2024-12-03 14:00:00",
    "remainTakeParcelTime": "23",
    "isAllowFinalInspection": null,
    "orderScenario": null,
    "hasCheckUniqueCodeOrder": null,
    "requestReceiptTime": "2024-12-14 14:27:14",
    "remainReceiptTime": "287",
    "boxNum": null,
    "materialTracingStatus": 2,
    "materialTracingStatusName": "未分配",
    "returnOrderInfo": {},
    "qcInfo": {},
    "preSaleExInfo": {},
    "deliveryInfo": {},
    "isScrap": 2,
    "lifeDays": 0,
    "isShelfLife": null,
    "refuseDay": null,
    "orderProductDetailID": null,
    "sourceOrderNo": "",
    "returnTime": "",
    "storeType": 2,
    "appealInfo": {},
    "suggestedReserveTime": "2024-12-03 11:30:00",
    "reconsiderMark": 0,
    "hasReconsiderOrder": false,
    "canDelivery": 0,
    "invalidOrder": 2,
    "invalidOperator": "",
    "invalidOrderTime": null,
    "locations": [],
    "remark": "",
    "uniqueCodeOrder": 2,
    "shippingDesk": 2,
    "stockLabel": 0,
    "supplierCode": "1",
    "reconsiderOrderState": null,
    "reconsiderOrderStateName": null,
    "jitOrderNo": [
      "PP2410210000001"
    ],
    "reservationInfo": {},
    "needQuantity": 1,
    "suffixZh": "明亮-M(中文)",
    "subSuffixZh": "M(中文)",
    "skuCode": "I9bqmdwce10i",
    "billState": 0,
    "skuThumb": "",
    "billStateName": "未维护",
    "orderQuantity": 1,
    "deliveryQuantity": null,
    "storageQuantity": null,
    "defectiveQuantity": null,
    "receiptQuantity": null,
    "groundingQuantity": null,
    "returnPlanQuantity": null,
    "supplierSku": "",
    "supplyPrice": 14.64,
    "tempDeliveryQuantity": 0,
    "tempPackingDetail": null,
    "orderExt": {
      "skcName": "ss22120144519212",
      "goodsSupplyStatus": 1,
      "skuList": [
        {
          "skuCode": "I9bqmdwce10i",
          "list": [
            {
              "supplierWarehouseId": 80917,
              "supplierWarehouseName": "总仓",
              "inventoryNum": -15458
            },
            {
              "supplierWarehouseId": 87575,
              "supplierWarehouseName": "佛山仓",
              "inventoryNum": -1732
            }
          ],
          "inventoryAbleSaleDays": 0
        }
      ],
      "isRisk": 0
    }
  },
]
